-- ============================================================================
-- 03_vw_search_requests.sql
-- Deterministic modular extraction
-- Guarantees:
--   ✔ Zero skipped statements
--   ✔ No duplicate SQL within file
--   ✔ Ordered deployment sequence
-- ============================================================================

--   View:         VW_<DOMAIN>_<DESCRIPTION>     (e.g. VW_SEARCH_REQUESTS)
-- │   Filter: RECORD['name']::STRING = 'CORTEX_SEARCH_REQUEST'               │
-- VW_SEARCH_REQUESTS: Foundation view that parses raw JSON events into typed columns.
-- Filter: Only CORTEX_SEARCH_REQUEST events (excludes other AI service events)
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS AS
  AND RECORD['name']::STRING = 'CORTEX_SEARCH_REQUEST';
FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS
    FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS
      AND RECORD['name']::STRING = 'CORTEX_SEARCH_REQUEST'
          AND RECORD['name']::STRING = 'CORTEX_SEARCH_REQUEST'
  AND RECORD['name']::STRING = 'CORTEX_SEARCH_REQUEST'
-- Optimization: For dashboards, query VW_SEARCH_REQUESTS instead of raw event table.
-- ALTER VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS
--   VW_SEARCH_REQUESTS        - Base parsed events
-- 10B. [CRITICAL] DEFENSIVE EVENT PARSING (REPLACES VW_SEARCH_REQUESTS)
FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS;
        FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS
     'SELECT DATE_TRUNC(''day'', event_timestamp) AS day, COUNT(*) AS requests FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS WHERE event_timestamp >= DATEADD(''day'', -7, CURRENT_TIMESTAMP()) GROUP BY day ORDER BY day',
        COUNT_IF(RECORD['name']::STRING = 'CORTEX_SEARCH_REQUEST') AS search_events,
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS_TRACED AS
WHERE RECORD['name']::STRING = 'CORTEX_SEARCH_REQUEST'
--   VW_SEARCH_REQUESTS_TRACED     - Base view with request_id traceability
ALTER VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS
      AND e.RECORD['name']::STRING = 'CORTEX_SEARCH_REQUEST'
          AND e.RECORD['name']::STRING = 'CORTEX_SEARCH_REQUEST'
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS_TZ AS
WHERE RECORD['name']::STRING = 'CORTEX_SEARCH_REQUEST';
--   VW_SEARCH_REQUESTS_TZ            - Timezone-converted base view
--   MP_QUERY_TEXT_REDACT → VW_SEARCH_REQUESTS.query_text (now active)
      AND RECORD['name']::STRING = 'CORTEX_SEARCH_REQUEST';
            'CORTEX_SEARCH_REQUEST events exist in last 7 days',
    WHERE RECORD['name']::STRING = 'CORTEX_SEARCH_REQUEST'
    -- T3.1: VW_SEARCH_REQUESTS compiles and returns data
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS LIMIT 1;
    VALUES (:suite_run_id, 'T3_MONITORING_VIEWS', 'T3.1', 'VW_SEARCH_REQUESTS Queryable',
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS;
            'VW_SEARCH_REQUESTS COUNT completes within 30 seconds',
    FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS;
            'Raw event count matches VW_SEARCH_REQUESTS count',
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS_STABLE AS
FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS_STABLE
--   VW_SEARCH_REQUESTS_STABLE      - 3-min buffer for alert safety
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS_ENHANCED AS
    (SELECT COUNT(*) FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_REQUESTS) AS events_in_window,
--   VW_SEARCH_REQUESTS_ENHANCED    - Fingerprint + ingestion lag + cleaned query