-- ============================================================================
-- 04_monitoring_views.sql
-- Deterministic modular extraction
-- Guarantees:
--   ✔ Zero skipped statements
--   ✔ No duplicate SQL within file
--   ✔ Ordered deployment sequence
-- ============================================================================

-- Author: Principal Snowflake Architect & AI Observability Expert
--   Table:        TBL_<DOMAIN>_<DESCRIPTION>    (e.g. TBL_DAILY_SEARCH_METRICS)
--   Alert:        ALT_<TRIGGER>_<METRIC>        (e.g. ALT_SPIKE_ERROR_RATE)
--   • Proactive performance monitoring prevents user-impacting degradation
-- │              OBSERVABILITY INGESTION LAYER                                │
-- │                    MONITORING LAYER                                       │
-- │  • Snowflake ALERTs  │  │  • Snowsight dashboards                    │
  COMMENT = 'Full governance access to AI observability data including sensitive query text';
-- 3C. OBSERVABILITY DATA MODELING
-- 3D. BUILD MONITORING VIEWS
-- All downstream views depend on this. Rolling 7-day window for real-time monitoring.
    RECORD_ATTRIBUTES['snow.ai.observability.object.name']::STRING                     AS service_name,
    RECORD_ATTRIBUTES['snow.ai.observability.user.name']::STRING                       AS user_name,
    RECORD_ATTRIBUTES['snow.ai.observability.role.name']::STRING                       AS role_name,
    VALUE['snow.ai.observability.request_body']['query']::STRING                        AS query_text,
    VALUE['snow.ai.observability.response_time_ms']::NUMBER                            AS response_time_ms,
    VALUE['snow.ai.observability.response_status_code']::NUMBER                        AS status_code,
    VALUE['snow.ai.observability.request_body']['limit']::NUMBER                        AS result_limit,
    VALUE['snow.ai.observability.operation_type']::STRING                               AS operation_type,
-- VW_SLOW_QUERIES: Surfaces requests exceeding the 2000ms latency SLA threshold.
-- Action: Investigate service load, index freshness, or network latency.
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SLOW_QUERIES AS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_FAILED_REQUESTS AS
-- VW_TOP_USERS: Ranks users by request volume with latency and error statistics.
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_TOP_USERS AS
    AVG(response_time_ms)               AS avg_latency_ms,
    MAX(response_time_ms)               AS max_latency_ms,
-- VW_SERVICE_METRICS: Hourly performance percentiles (P50/P95/P99) per service.
-- Use case: SLA monitoring, trend analysis, executive dashboards.
-- Key metric: error_rate_pct triggers ALT_SPIKE_ERROR_RATE when > 5%.
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SERVICE_METRICS AS
    AVG(response_time_ms)                AS avg_latency_ms,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY response_time_ms) AS p50_latency_ms,
    PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY response_time_ms) AS p95_latency_ms,
    PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY response_time_ms) AS p99_latency_ms,
    MAX(response_time_ms)                AS max_latency_ms,
-- Use case: Week-over-week growth tracking, adoption metrics, capacity forecasting.
-- Best consumed via Snowsight dashboards or Power BI for trend visualization.
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_DAILY_TRENDS AS
-- 3E. PERFORMANCE MONITORING FRAMEWORK (SLA TRACKING)
CREATE OR REPLACE TABLE PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_SLA_DEFINITIONS (
    sla_metric           STRING,
INSERT INTO PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_SLA_DEFINITIONS
    (service_name, sla_metric, threshold_value, severity)
    ('product_search', 'p95_latency_ms', 1500, 'warning'),
    ('product_search', 'p99_latency_ms', 3000, 'critical'),
    ('knowledge_base_search', 'p95_latency_ms', 2000, 'warning'),
    ('knowledge_base_search', 'p99_latency_ms', 5000, 'critical'),
-- VW_SLA_COMPLIANCE: Real-time SLA breach detection comparing live metrics vs thresholds.
-- Computes current P95, P99, and error rate for the last 1 hour per service.
-- Output: COMPLIANT or BREACHED status per metric. Feeds executive reporting.
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SLA_COMPLIANCE AS
WITH current_metrics AS (
        PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY response_time_ms) AS p95_latency_ms,
        PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY response_time_ms) AS p99_latency_ms,
    s.sla_metric,
    CASE s.sla_metric
        WHEN 'p95_latency_ms' THEN m.p95_latency_ms
        WHEN 'p99_latency_ms' THEN m.p99_latency_ms
        WHEN CASE s.sla_metric
                WHEN 'p95_latency_ms' THEN m.p95_latency_ms
                WHEN 'p99_latency_ms' THEN m.p99_latency_ms
FROM PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_SLA_DEFINITIONS s
LEFT JOIN current_metrics m ON s.service_name = m.service_name;
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_ACTUAL_SERVICE_COSTS AS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_COST_BY_USER AS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_COST_BY_SERVICE AS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_CHARGEBACK_BY_ROLE AS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SERVING_HOURLY_COSTS AS
-- ALT_SPIKE_LATENCY: Fires when P95 latency exceeds 3000ms in any 15-minute window.
CREATE OR REPLACE ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_SPIKE_LATENCY
    GROUP BY RECORD_ATTRIBUTES['snow.ai.observability.object.name']::STRING
    HAVING PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY VALUE['snow.ai.observability.response_time_ms']::NUMBER) > 3000
      'P95 latency exceeded 3000ms threshold in the last 15 minutes. Investigate immediately.'
ALTER ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_SPIKE_LATENCY RESUME;
-- ALT_SPIKE_ERROR_RATE: Fires when error rate exceeds 5% with minimum 10 requests.
CREATE OR REPLACE ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_SPIKE_ERROR_RATE
       AND COUNT_IF(VALUE['snow.ai.observability.response_status_code']::NUMBER != 200) * 1.0 / COUNT(*) > 0.05
      'Error rate exceeded 5% in the last 10 minutes. Check service health.'
ALTER ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_SPIKE_ERROR_RATE RESUME;
CREATE OR REPLACE ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_SPIKE_VOLUME
ALTER ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_SPIKE_VOLUME RESUME;
-- TBL_DAILY_SEARCH_METRICS: Pre-computed daily rollups for long-term trend analysis.
-- Purpose: BI dashboards, monthly executive reports, year-over-year comparisons.
CREATE OR REPLACE TABLE PRD_CORTEX_OBSERVABILITY.AGGREGATED.TBL_DAILY_SEARCH_METRICS (
    metric_date          DATE,
    avg_latency_ms       FLOAT,
    p50_latency_ms       FLOAT,
    p95_latency_ms       FLOAT,
    p99_latency_ms       FLOAT,
    max_latency_ms       FLOAT,
-- TBL_DAILY_SEARCH_METRICS. Runs at 01:00 UTC to capture full previous day.
CREATE OR REPLACE TASK PRD_CORTEX_OBSERVABILITY.MONITORING.TSK_DAILY_AGGREGATION
INSERT INTO PRD_CORTEX_OBSERVABILITY.AGGREGATED.TBL_DAILY_SEARCH_METRICS
    (metric_date, service_name, user_name, role_name, total_requests,
     avg_latency_ms, p50_latency_ms, p95_latency_ms, p99_latency_ms,
     max_latency_ms, error_count, error_rate_pct, unique_queries)
    CURRENT_DATE() - 1                                                                     AS metric_date,
    RECORD_ATTRIBUTES['snow.ai.observability.object.name']::STRING                         AS service_name,
    RECORD_ATTRIBUTES['snow.ai.observability.user.name']::STRING                           AS user_name,
    RECORD_ATTRIBUTES['snow.ai.observability.role.name']::STRING                           AS role_name,
    AVG(VALUE['snow.ai.observability.response_time_ms']::NUMBER)                           AS avg_latency_ms,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY VALUE['snow.ai.observability.response_time_ms']::NUMBER) AS p50_latency_ms,
    PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY VALUE['snow.ai.observability.response_time_ms']::NUMBER) AS p95_latency_ms,
    PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY VALUE['snow.ai.observability.response_time_ms']::NUMBER) AS p99_latency_ms,
    MAX(VALUE['snow.ai.observability.response_time_ms']::NUMBER)                           AS max_latency_ms,
    COUNT_IF(VALUE['snow.ai.observability.response_status_code']::NUMBER != 200)           AS error_count,
    ROUND(COUNT_IF(VALUE['snow.ai.observability.response_status_code']::NUMBER != 200) / NULLIF(COUNT(*), 0) * 100, 2) AS error_rate_pct,
    COUNT(DISTINCT VALUE['snow.ai.observability.request_body']['query']::STRING)            AS unique_queries
ALTER TASK PRD_CORTEX_OBSERVABILITY.MONITORING.TSK_DAILY_AGGREGATION RESUME;
CREATE OR REPLACE TASK PRD_CORTEX_OBSERVABILITY.MONITORING.TSK_MONTHLY_RETENTION_CLEANUP
DELETE FROM PRD_CORTEX_OBSERVABILITY.AGGREGATED.TBL_DAILY_SEARCH_METRICS
WHERE metric_date < DATEADD('year', -2, CURRENT_DATE());
ALTER TASK PRD_CORTEX_OBSERVABILITY.MONITORING.TSK_MONTHLY_RETENTION_CLEANUP RESUME;
-- 3I. INTEGRATION WITH BI / MONITORING TOOLS
-- For Snowsight: Use the views directly in worksheets/dashboards
-- CREATE OR REPLACE SHARE SHR_CORTEX_OBSERVABILITY;
    VALUE['snow.ai.observability.request_body']['query']::STRING AS query_text,
    AVG(VALUE['snow.ai.observability.response_time_ms']::NUMBER) AS avg_latency_ms
    RECORD_ATTRIBUTES['snow.ai.observability.object.name']::STRING AS service,
    RECORD_ATTRIBUTES['snow.ai.observability.user.name']::STRING AS user_name,
    VALUE['snow.ai.observability.response_time_ms']::NUMBER AS latency_ms
ORDER BY latency_ms DESC
    VALUE['snow.ai.observability.response_status_code']::NUMBER AS status_code,
  AND VALUE['snow.ai.observability.response_status_code']::NUMBER != 200
CREATE OR REPLACE MASKING POLICY PRD_CORTEX_OBSERVABILITY.GOVERNANCE.MP_QUERY_TEXT_REDACT
      LEFT(PRD_CORTEX_OBSERVABILITY.GOVERNANCE.REDACT_SENSITIVE_QUERY(val), 10) || '***REDACTED***'
--   MODIFY COLUMN query_text SET MASKING POLICY PRD_CORTEX_OBSERVABILITY.GOVERNANCE.MP_QUERY_TEXT_REDACT;
-- Prevents cross-tenant data leakage in VW_TENANT_METRICS and VW_COST_BY_USER.
CREATE OR REPLACE ROW ACCESS POLICY PRD_CORTEX_OBSERVABILITY.GOVERNANCE.RAP_TENANT_ISOLATION
-- ALTER VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_TENANT_METRICS
--   ADD ROW ACCESS POLICY PRD_CORTEX_OBSERVABILITY.GOVERNANCE.RAP_TENANT_ISOLATION ON (tenant_identifier);
-- ALTER VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_COST_BY_USER
--   ADD ROW ACCESS POLICY PRD_CORTEX_OBSERVABILITY.GOVERNANCE.RAP_TENANT_ISOLATION ON (role_name);
-- Note: ACCOUNT_USAGE views have ~45 min latency; not real-time.
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.GOVERNANCE.VW_ACCESS_AUDIT AS
WHERE ARRAY_CONTAINS('PRD_CORTEX_OBSERVABILITY'::VARIANT,
--   • Estimated: 5-15 credits/day for full monitoring stack
--   • Query aggregated tables for dashboards (not raw events)
--   • Cache frequently accessed metrics in materialized views
--    • Never query raw event table for dashboards at scale
--    • Dedicated roles for observability access
-- │ Monitoring overhead        │ Dedicated PRD_CORTEX_OBS_XS_WH, bounded     │
-- │ Cost overrun               │ Budget monitoring, resource monitors         │
--   * Deploy base monitoring views
-- LEVEL 2 - MONITORING DASHBOARDS (Week 3-4):
--   * Deploy VW_SERVICE_METRICS, VW_DAILY_TRENDS
--   * Create Snowsight dashboards for ops team
--   * Deploy ALT_SPIKE_LATENCY, ALT_SPIKE_ERROR_RATE, ALT_SPIKE_VOLUME
-- Views (MONITORING):
--   VW_SLOW_QUERIES           - Queries > 2s latency
--   VW_SERVICE_METRICS        - Hourly P50/P95/P99 per service
--   TBL_DAILY_SEARCH_METRICS  - Long-term aggregated metrics
--   ALT_SPIKE_LATENCY        - P95 > 3000ms (5 min check)
--   ALT_SPIKE_ERROR_RATE     - Error rate > 5% (5 min check)
--   VW_ACCESS_AUDIT           - Who accessed observability data
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.WAIT_FOR_EVENTS(expected_count INT)
    TRY_CAST(RECORD_ATTRIBUTES['snow.ai.observability.object.name']::STRING AS STRING) AS service_name,
    TRY_CAST(RECORD_ATTRIBUTES['snow.ai.observability.user.name']::STRING AS STRING)   AS user_name,
    TRY_CAST(RECORD_ATTRIBUTES['snow.ai.observability.role.name']::STRING AS STRING)   AS role_name,
    COALESCE(VALUE['snow.ai.observability.request_body']['query']::STRING, 'NULL_QUERY') AS query_text,
    COALESCE(TRY_CAST(VALUE['snow.ai.observability.response_time_ms']::STRING AS NUMBER), -1) AS response_time_ms,
    COALESCE(TRY_CAST(VALUE['snow.ai.observability.response_status_code']::STRING AS NUMBER), -1) AS status_code,
    TRY_CAST(VALUE['snow.ai.observability.request_body']['limit']::STRING AS NUMBER)   AS result_limit,
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.VALIDATE_OBSERVABILITY_PREREQUISITES()
-- 10D. [HIGH] RESOURCE MONITOR & BUDGET CONTROLS
CREATE RESOURCE MONITOR IF NOT EXISTS RM_CORTEX_OBSERVABILITY
  SET RESOURCE_MONITOR = RM_CORTEX_OBSERVABILITY;
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_DAILY_OBSERVABILITY_COSTS AS
CREATE OR REPLACE FUNCTION PRD_CORTEX_OBSERVABILITY.MONITORING.NORMALIZE_QUERY(query_text STRING)
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_WITH_FINGERPRINTS AS
    PRD_CORTEX_OBSERVABILITY.MONITORING.NORMALIZE_QUERY(query_text) AS query_fingerprint,
    COUNT(*) OVER (PARTITION BY PRD_CORTEX_OBSERVABILITY.MONITORING.NORMALIZE_QUERY(query_text)) AS fingerprint_frequency
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_VOLUME_FORECAST AS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_ANOMALY_DETECTION AS
-- 10H. [LOW] PRE-DEFINED DASHBOARD QUERIES
CREATE OR REPLACE TABLE PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_DASHBOARD_QUERIES (
    dashboard_name STRING,
INSERT INTO PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_DASHBOARD_QUERIES
    (dashboard_name, query_name, sql_text, refresh_rate_minutes, created_by)
    ('Executive Dashboard', 'Weekly Request Trends',
    ('Operations Dashboard', 'Current SLA Status',
     'SELECT * FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SLA_COMPLIANCE WHERE sla_status = ''BREACHED''',
    ('Finance Dashboard', 'Monthly Cost by Service',
     'SELECT * FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_COST_BY_SERVICE WHERE usage_month = DATE_TRUNC(''month'', CURRENT_TIMESTAMP())',
-- 10I. [LOW] DATA QUALITY MONITORING
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_DATA_QUALITY AS
        COUNT_IF(RECORD_ATTRIBUTES['snow.ai.observability.object.name'] IS NULL) AS null_service_name,
        COUNT_IF(VALUE['snow.ai.observability.response_time_ms'] IS NULL) AS null_latency,
        COUNT_IF(VALUE['snow.ai.observability.response_status_code'] IS NULL) AS null_status_code
    null_latency,
        WHEN null_latency > total_events * 0.10 THEN 'WARNING'
--   VALIDATE_OBSERVABILITY_PREREQUISITES - Health check before operations
-- NEW Resource Monitor:
--   RM_CORTEX_OBSERVABILITY            - 500 credit/month budget control
-- NEW Views (MONITORING):
--   VW_DATA_QUALITY                    - Event data quality monitoring
--   TBL_DASHBOARD_QUERIES              - Pre-defined dashboard SQL registry
    TRY_CAST(RECORD_ATTRIBUTES['snow.ai.observability.object.name']::STRING AS STRING)   AS service_name,
    TRY_CAST(RECORD_ATTRIBUTES['snow.ai.observability.user.name']::STRING AS STRING)     AS user_name,
    TRY_CAST(RECORD_ATTRIBUTES['snow.ai.observability.role.name']::STRING AS STRING)     AS role_name,
    COALESCE(VALUE['snow.ai.observability.request_body']['query']::STRING, 'NULL_QUERY')  AS query_text,
    TRY_CAST(VALUE['snow.ai.observability.request_body']['limit']::STRING AS NUMBER)     AS result_limit,
    VALUE['snow.ai.observability.request_body']['request_id']::STRING                    AS request_id,
    VALUE['snow.ai.observability.request_body']['session_id']::STRING                    AS session_id,
    VALUE['snow.ai.observability.operation_type']::STRING                                AS operation_type,
-- 11B. QUERY QUALITY & SEARCH EFFECTIVENESS METRICS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_QUERY_QUALITY AS
    AVG(response_time_ms) AS avg_latency_ms,
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_USER_FRUSTRATION_SIGNALS AS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_TRUE_COST_ATTRIBUTION AS
CREATE OR REPLACE FUNCTION PRD_CORTEX_OBSERVABILITY.GOVERNANCE.REDACT_SENSITIVE_QUERY(query_text STRING)
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.GOVERNANCE.VW_PII_AUDIT AS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_ABUSE_DETECTION AS
        RECORD_ATTRIBUTES['snow.ai.observability.user.name']::STRING AS user_name,
        RECORD_ATTRIBUTES['snow.ai.observability.role.name']::STRING AS role_name,
        RECORD_ATTRIBUTES['snow.ai.observability.object.name']::STRING AS service_name,
CREATE OR REPLACE ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_ABUSE_DETECTED
    FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_ABUSE_DETECTION
ALTER ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_ABUSE_DETECTED RESUME;
-- 11F. LATENCY ROOT CAUSE BREAKDOWN
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_LATENCY_ANALYSIS AS
    ROUND(AVG(response_time_ms), 2) AS avg_latency_ms,
    MAX(response_time_ms) AS max_latency_ms,
    END AS latency_health,
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_LATENCY_BUCKETED AS
    END AS latency_bucket,
CREATE OR REPLACE TABLE PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_SERVICE_FRESHNESS_LOG (
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.LOG_SERVICE_FRESHNESS()
    INSERT INTO PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_SERVICE_FRESHNESS_LOG
CREATE OR REPLACE TASK PRD_CORTEX_OBSERVABILITY.MONITORING.TSK_FRESHNESS_CHECK
  CALL PRD_CORTEX_OBSERVABILITY.MONITORING.LOG_SERVICE_FRESHNESS();
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_FRESHNESS_STATUS AS
FROM PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_SERVICE_FRESHNESS_LOG
CREATE OR REPLACE ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_STALE_INDEX
    FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_FRESHNESS_STATUS
ALTER ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_STALE_INDEX RESUME;
CREATE OR REPLACE TABLE PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_CHAOS_TEST_RESULTS (
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.RUN_CHAOS_TEST_SUITE()
    -- Test 1: Verify alerts fire on high latency simulation
    INSERT INTO PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_CHAOS_TEST_RESULTS
        'Checked ALT_SPIKE_LATENCY exists' AS details
        FROM PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_CHAOS_TEST_RESULTS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SERVICE_REGISTRY AS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_TENANT_METRICS AS
    ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY response_time_ms), 2) AS p95_latency_ms,
        ('snow.ai.observability.object.name', 'STRING'),
        ('snow.ai.observability.user.name', 'STRING'),
        ('snow.ai.observability.role.name', 'STRING'),
        ('snow.ai.observability.response_time_ms', 'NUMBER'),
        ('snow.ai.observability.response_status_code', 'NUMBER')
CREATE OR REPLACE MATERIALIZED VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.MVW_HOURLY_SERVICE_METRICS AS
    RECORD_ATTRIBUTES['snow.ai.observability.object.name']::STRING AS service_name,
    AVG(TRY_TO_NUMBER(VALUE['snow.ai.observability.response_time_ms']::STRING)) AS avg_latency_ms,
    COUNT_IF(TRY_TO_NUMBER(VALUE['snow.ai.observability.response_status_code']::STRING) != 200) AS error_count
CREATE OR REPLACE MATERIALIZED VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.MVW_DAILY_TRENDS AS
    MAX(TRY_TO_NUMBER(VALUE['snow.ai.observability.response_time_ms']::STRING)) AS max_latency_ms,
-- 11L. EXECUTIVE DASHBOARD VIEWS (CFO/CTO/OPS/PRODUCT)
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_EXEC_DASHBOARD AS
    'TOTAL_REQUESTS_7D' AS metric_name,
    COUNT(*)::STRING AS metric_value,
    'Error rate in last 24 hours'
    'P95_LATENCY_24H',
    'P95 latency (ms) in last 24 hours'
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_ADOPTION_TREND AS
--   VW_LATENCY_ANALYSIS           - Hourly percentile breakdown
--   VW_LATENCY_BUCKETED           - Per-request latency classification
--   VW_FRESHNESS_STATUS           - Index staleness monitoring
--   VW_TENANT_METRICS             - Multi-tenant per-role metrics
--   VW_EXEC_DASHBOARD             - CTO/CFO KPI summary
--   VW_ADOPTION_TREND             - Week-over-week growth metrics
--   MVW_HOURLY_SERVICE_METRICS    - Pre-computed hourly aggregates
CREATE SECRET IF NOT EXISTS PRD_CORTEX_OBSERVABILITY.GOVERNANCE.SEC_ALERT_EMAIL
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_SEND_ALERT(
    email := (SELECT SYSTEM$GET_SECRET('PRD_CORTEX_OBSERVABILITY.GOVERNANCE.SEC_ALERT_EMAIL'));
  SET MASKING POLICY PRD_CORTEX_OBSERVABILITY.GOVERNANCE.MP_QUERY_TEXT_REDACT;
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_DAILY_AGGREGATION()
    DELETE FROM PRD_CORTEX_OBSERVABILITY.AGGREGATED.TBL_DAILY_SEARCH_METRICS
    WHERE metric_date = CURRENT_DATE() - 1;
    INSERT INTO PRD_CORTEX_OBSERVABILITY.AGGREGATED.TBL_DAILY_SEARCH_METRICS
        (metric_date, service_name, total_requests, unique_users,
         avg_latency_ms, p95_latency_ms, error_count, error_rate_pct, total_estimated_credits)
        CURRENT_DATE() - 1 AS metric_date,
        COUNT(DISTINCT RECORD_ATTRIBUTES['snow.ai.observability.user.name']::STRING) AS unique_users,
        ROUND(AVG(TRY_TO_NUMBER(VALUE['snow.ai.observability.response_time_ms']::STRING)), 2) AS avg_latency_ms,
        ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY TRY_TO_NUMBER(VALUE['snow.ai.observability.response_time_ms']::STRING)), 2) AS p95_latency_ms,
        COUNT_IF(TRY_TO_NUMBER(VALUE['snow.ai.observability.response_status_code']::STRING) != 200) AS error_count,
    LEFT JOIN PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TBL_PRICING_CONFIG pc
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_BACKFILL_AGGREGATION(
        DELETE FROM PRD_CORTEX_OBSERVABILITY.AGGREGATED.TBL_DAILY_SEARCH_METRICS
        WHERE metric_date = :current_dt;
        INSERT INTO PRD_CORTEX_OBSERVABILITY.AGGREGATED.TBL_DAILY_SEARCH_METRICS
            (metric_date, service_name, total_requests, unique_users,
             avg_latency_ms, p95_latency_ms, error_count, error_rate_pct, total_estimated_credits)
            :current_dt AS metric_date,
            RECORD_ATTRIBUTES['snow.ai.observability.object.name']::STRING AS service_name,
            COUNT(DISTINCT RECORD_ATTRIBUTES['snow.ai.observability.user.name']::STRING) AS unique_users,
            ROUND(AVG(TRY_TO_NUMBER(VALUE['snow.ai.observability.response_time_ms']::STRING)), 2),
            ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY TRY_TO_NUMBER(VALUE['snow.ai.observability.response_time_ms']::STRING)), 2),
            COUNT_IF(TRY_TO_NUMBER(VALUE['snow.ai.observability.response_status_code']::STRING) != 200),
            ROUND(100.0 * COUNT_IF(TRY_TO_NUMBER(VALUE['snow.ai.observability.response_status_code']::STRING) != 200) / NULLIF(COUNT(*), 0), 2),
        LEFT JOIN PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TBL_PRICING_CONFIG pc
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_VOLUME_BASELINE AS
CREATE OR REPLACE ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_VOLUME_SPIKE_CONTEXTUAL
    JOIN PRD_CORTEX_OBSERVABILITY.MONITORING.VW_VOLUME_BASELINE bl
    CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_SEND_ALERT(
ALTER ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_VOLUME_SPIKE_CONTEXTUAL RESUME;
CREATE TABLE IF NOT EXISTS PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TBL_PRICING_CONFIG (
MERGE INTO PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TBL_PRICING_CONFIG tgt
CREATE OR REPLACE STREAM PRD_CORTEX_OBSERVABILITY.MONITORING.STR_AI_EVENTS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_STREAM_ALERT_CHECK AS
    COUNT_IF(TRY_TO_NUMBER(VALUE['snow.ai.observability.response_time_ms']::STRING) > 3000) AS high_latency_count,
    COUNT_IF(TRY_TO_NUMBER(VALUE['snow.ai.observability.response_status_code']::STRING) != 200) AS error_count,
FROM PRD_CORTEX_OBSERVABILITY.MONITORING.STR_AI_EVENTS
-- 12I. COST & PERFORMANCE: RESOURCE MONITOR (SAFETY NET)
CREATE RESOURCE MONITOR IF NOT EXISTS RM_CORTEX_OBS_MONTHLY
  SET RESOURCE_MONITOR = RM_CORTEX_OBS_MONTHLY;
-- 12J. PIPELINE HEALTH: SELF-MONITORING OF THE OBSERVABILITY STACK
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_PIPELINE_HEALTH AS
    MAX(metric_date) AS last_success_date,
    DATEDIFF('hour', MAX(metric_date)::TIMESTAMP_NTZ, CURRENT_TIMESTAMP()) AS hours_since_last_run,
        WHEN DATEDIFF('hour', MAX(metric_date)::TIMESTAMP_NTZ, CURRENT_TIMESTAMP()) > 48 THEN 'CRITICAL'
        WHEN DATEDIFF('hour', MAX(metric_date)::TIMESTAMP_NTZ, CURRENT_TIMESTAMP()) > 26 THEN 'STALE'
FROM PRD_CORTEX_OBSERVABILITY.AGGREGATED.TBL_DAILY_SEARCH_METRICS
        WHEN SYSTEM$STREAM_HAS_DATA('PRD_CORTEX_OBSERVABILITY.MONITORING.STR_AI_EVENTS') THEN 'PENDING_DATA'
CREATE OR REPLACE ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_PIPELINE_STALE
    FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_PIPELINE_HEALTH
      'CRITICAL: Observability Pipeline Stale',
      'The monitoring pipeline itself has stopped receiving or processing events. Immediate investigation required.'
ALTER ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_PIPELINE_STALE RESUME;
CREATE OR REPLACE TABLE PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TBL_ENVIRONMENT_CONFIG (
INSERT INTO PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TBL_ENVIRONMENT_CONFIG (env_key, env_value, description)
    ('ALERT_EMAIL_SECRET', 'PRD_CORTEX_OBSERVABILITY.GOVERNANCE.SEC_ALERT_EMAIL', 'Secret for alert routing'),
-- NEW Procedures (MONITORING):
--   VW_PIPELINE_HEALTH               - Self-monitoring of obs stack
-- NEW Streams (MONITORING):
-- NEW Resource Monitors:
-- NEW Alerts (MONITORING):
--   ALT_PIPELINE_STALE               - Self-monitoring critical alert
-- ║ 13. PRODUCTION-GRADE REAL-TIME OBSERVABILITY TEST SUITE                       ║
-- ║   Validates every layer of the observability stack in production.              ║
-- ║   CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_RUN_FULL_TEST_SUITE();          ║
-- ║   T2  - Event Ingestion (table access, data flow, latency)                   ║
-- ║   T9  - Performance (materialized views, stream, resource monitor)            ║
-- ║   T10 - Pipeline Health (self-monitoring, freshness, anomaly detection)       ║
CREATE OR REPLACE TABLE PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_TEST_RESULTS (
CREATE OR REPLACE TABLE PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_TEST_SUITE_RUNS (
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T1_INFRASTRUCTURE(suite_run_id STRING)
    INSERT INTO PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_TEST_RESULTS
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T2_EVENT_INGESTION(suite_run_id STRING)
    -- T2.4: Events present in monitoring window
            'Search events exist within the 7-day monitoring window',
          AND RECORD_ATTRIBUTES['snow.ai.observability.object.name'] IS NOT NULL
          AND VALUE['snow.ai.observability.response_time_ms'] IS NOT NULL
        test_result := (SELECT SYSTEM$STREAM_HAS_DATA('PRD_CORTEX_OBSERVABILITY.MONITORING.STR_AI_EVENTS') IS NOT NULL);
-- 13D. T3 - MONITORING VIEWS VALIDATION
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T3_MONITORING_VIEWS(suite_run_id STRING)
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SLOW_QUERIES LIMIT 1;
    SELECT :suite_run_id, 'T3_MONITORING_VIEWS', 'T3.2', 'VW_SLOW_QUERIES Queryable',
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_FAILED_REQUESTS LIMIT 1;
    SELECT :suite_run_id, 'T3_MONITORING_VIEWS', 'T3.3', 'VW_FAILED_REQUESTS Queryable',
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_TOP_USERS LIMIT 1;
    SELECT :suite_run_id, 'T3_MONITORING_VIEWS', 'T3.4', 'VW_TOP_USERS Queryable',
    -- T3.5: VW_SERVICE_METRICS compiles
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SERVICE_METRICS LIMIT 1;
    SELECT :suite_run_id, 'T3_MONITORING_VIEWS', 'T3.5', 'VW_SERVICE_METRICS Queryable',
            'Service metrics view compiles and executes',
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_DAILY_TRENDS LIMIT 1;
    SELECT :suite_run_id, 'T3_MONITORING_VIEWS', 'T3.6', 'VW_DAILY_TRENDS Queryable',
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_ANOMALY_DETECTION LIMIT 1;
    SELECT :suite_run_id, 'T3_MONITORING_VIEWS', 'T3.7', 'VW_ANOMALY_DETECTION Queryable',
    -- T3.8: VW_LATENCY_ANALYSIS compiles
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_LATENCY_ANALYSIS LIMIT 1;
    SELECT :suite_run_id, 'T3_MONITORING_VIEWS', 'T3.8', 'VW_LATENCY_ANALYSIS Queryable',
            'Latency analysis view compiles and executes',
    -- T3.9: VW_EXEC_DASHBOARD compiles
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_EXEC_DASHBOARD LIMIT 1;
    SELECT :suite_run_id, 'T3_MONITORING_VIEWS', 'T3.9', 'VW_EXEC_DASHBOARD Queryable',
            'Executive dashboard view compiles and executes',
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_DATA_QUALITY LIMIT 1;
    SELECT :suite_run_id, 'T3_MONITORING_VIEWS', 'T3.10', 'VW_DATA_QUALITY Queryable',
    RETURN 'T3_MONITORING_VIEWS: 10 tests completed';
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T4_SLA_FRAMEWORK(suite_run_id STRING)
    SELECT COUNT(*) INTO sla_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_SLA_DEFINITIONS;
        SELECT COUNT(*) INTO sla_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SLA_COMPLIANCE LIMIT 1;
    test_result := (SELECT COUNT(*) = 0 FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SLA_COMPLIANCE
    test_result := (SELECT COUNT(*) = 0 FROM PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_SLA_DEFINITIONS
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T5_COST_GOVERNANCE(suite_run_id STRING)
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TBL_PRICING_CONFIG;
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_COST_BY_USER LIMIT 1;
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_COST_BY_SERVICE LIMIT 1;
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_TRUE_COST_ATTRIBUTION LIMIT 1;
    -- T5.5: VW_DAILY_OBSERVABILITY_COSTS compiles
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_DAILY_OBSERVABILITY_COSTS LIMIT 1;
    SELECT :suite_run_id, 'T5_COST_GOVERNANCE', 'T5.5', 'VW_DAILY_OBSERVABILITY_COSTS Queryable',
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T6_ALERTING(suite_run_id STRING)
        SELECT COUNT(*) INTO alert_count FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "name" = 'ALT_SPIKE_LATENCY';
    SELECT :suite_run_id, 'T6_ALERTING', 'T6.1', 'ALT_SPIKE_LATENCY Exists',
            'Latency spike alert is registered',
            'Error rate spike alert is registered',
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T7_RETENTION(suite_run_id STRING)
    -- T7.1: TBL_DAILY_SEARCH_METRICS table exists
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.AGGREGATED.TBL_DAILY_SEARCH_METRICS LIMIT 1;
            'TBL_DAILY_SEARCH_METRICS is accessible',
        FROM PRD_CORTEX_OBSERVABILITY.AGGREGATED.TBL_DAILY_SEARCH_METRICS
        WHERE metric_date < DATEADD('year', -2, CURRENT_DATE());
            'No data older than 2 years in TBL_DAILY_SEARCH_METRICS',
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T8_SECURITY(suite_run_id STRING)
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.GOVERNANCE.VW_PII_AUDIT LIMIT 1;
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.GOVERNANCE.VW_ACCESS_AUDIT LIMIT 1;
        test_result := (SELECT PRD_CORTEX_OBSERVABILITY.GOVERNANCE.REDACT_SENSITIVE_QUERY('my password is 1234') = '***CREDENTIAL_DETECTED***');
        test_result := (SELECT COUNT(*) >= 5 FROM PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TBL_ENVIRONMENT_CONFIG);
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T9_PERFORMANCE(suite_run_id STRING)
    -- T9.1: MVW_HOURLY_SERVICE_METRICS is queryable
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.MVW_HOURLY_SERVICE_METRICS LIMIT 1;
    SELECT :suite_run_id, 'T9_PERFORMANCE', 'T9.1', 'MVW Hourly Metrics Queryable',
            'Materialized view MVW_HOURLY_SERVICE_METRICS executes',
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.MVW_DAILY_TRENDS LIMIT 1;
        test_result := (SELECT PRD_CORTEX_OBSERVABILITY.MONITORING.NORMALIZE_QUERY('test 123 query') = 'TEST <NUM> QUERY');
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T10_PIPELINE_HEALTH(suite_run_id STRING)
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_PIPELINE_HEALTH;
            'VW_PIPELINE_HEALTH returns monitoring status',
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_VOLUME_BASELINE LIMIT 1;
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SERVICE_REGISTRY;
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T11_RESILIENCE(suite_run_id STRING)
    -- T11.2: Negative latency values handled (COALESCE to -1)
    SELECT :suite_run_id, 'T11_RESILIENCE', 'T11.2', 'Missing Latency Defaulted',
            'NULL latency defaults to -1 via COALESCE',
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_QUERY_QUALITY LIMIT 10;
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_USER_FRUSTRATION_SIGNALS LIMIT 1;
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_ABUSE_DETECTION LIMIT 1;
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T12_INTEGRATION(suite_run_id STRING)
    -- T12.2: Exec dashboard produces all expected metrics
    SELECT COUNT(DISTINCT metric_name) INTO row_count
    FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_EXEC_DASHBOARD;
    SELECT :suite_run_id, 'T12_INTEGRATION', 'T12.2', 'Exec Dashboard Complete',
            'VW_EXEC_DASHBOARD produces all 5 KPI metrics',
            '>=5 metrics', :row_count::STRING || ' metrics', :test_result,
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_ADOPTION_TREND;
    -- T12.4: Multi-tenant view produces role-based metrics
        SELECT COUNT(*) INTO row_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_TENANT_METRICS LIMIT 1;
    SELECT :suite_run_id, 'T12_INTEGRATION', 'T12.4', 'Multi-Tenant Metrics Work',
            'VW_TENANT_METRICS produces per-role analytics',
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_RUN_FULL_TEST_SUITE()
    INSERT INTO PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_TEST_SUITE_RUNS (suite_run_id) VALUES (:suite_id);
    CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T1_INFRASTRUCTURE(:suite_id);
    CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T2_EVENT_INGESTION(:suite_id);
    CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T3_MONITORING_VIEWS(:suite_id);
    CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T4_SLA_FRAMEWORK(:suite_id);
    CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T5_COST_GOVERNANCE(:suite_id);
    CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T6_ALERTING(:suite_id);
    CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T7_RETENTION(:suite_id);
    CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T8_SECURITY(:suite_id);
    CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T9_PERFORMANCE(:suite_id);
    CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T10_PIPELINE_HEALTH(:suite_id);
    CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T11_RESILIENCE(:suite_id);
    CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T12_INTEGRATION(:suite_id);
    SELECT COUNT(*) INTO total FROM PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_TEST_RESULTS WHERE test_suite_run_id = :suite_id;
    SELECT COUNT(*) INTO pass_count FROM PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_TEST_RESULTS WHERE test_suite_run_id = :suite_id AND passed = TRUE;
    UPDATE PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_TEST_SUITE_RUNS
        FROM PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_TEST_RESULTS
CREATE OR REPLACE TASK PRD_CORTEX_OBSERVABILITY.MONITORING.TSK_HOURLY_TEST_SUITE
  CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_RUN_FULL_TEST_SUITE();
ALTER TASK PRD_CORTEX_OBSERVABILITY.MONITORING.TSK_HOURLY_TEST_SUITE RESUME;
CREATE OR REPLACE ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_TEST_SUITE_FAILURES
    FROM PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_TEST_SUITE_RUNS
      'ALERT: Observability Test Suite Has Failures',
ALTER ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_TEST_SUITE_FAILURES RESUME;
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_TEST_SUITE_SUMMARY AS
FROM PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_TEST_SUITE_RUNS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_TEST_FAILURES_LATEST AS
FROM PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_TEST_RESULTS tr
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_TEST_TREND AS
FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_TEST_SUITE_SUMMARY
CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_RUN_FULL_TEST_SUITE();
-- SELECT * FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_TEST_SUITE_SUMMARY LIMIT 5;
-- SELECT * FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_TEST_FAILURES_LATEST;
-- SELECT * FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_TEST_TREND;
-- CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T1_INFRASTRUCTURE(UUID_STRING());
-- CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T2_EVENT_INGESTION(UUID_STRING());
-- CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T3_MONITORING_VIEWS(UUID_STRING());
-- CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T4_SLA_FRAMEWORK(UUID_STRING());
-- CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T5_COST_GOVERNANCE(UUID_STRING());
-- CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T6_ALERTING(UUID_STRING());
-- CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T7_RETENTION(UUID_STRING());
-- CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T8_SECURITY(UUID_STRING());
-- CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T9_PERFORMANCE(UUID_STRING());
-- CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T10_PIPELINE_HEALTH(UUID_STRING());
-- CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T11_RESILIENCE(UUID_STRING());
-- CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_TEST_T12_INTEGRATION(UUID_STRING());
--   SP_TEST_T3_MONITORING_VIEWS   - 10 tests (all monitoring views compile)
--   SP_TEST_T12_INTEGRATION       - 5 tests (E2E flow, dashboard, object count)
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_SEND_CXO_REPORT(
    avg_latency NUMBER;
    INTO total_requests, distinct_services, distinct_users, avg_latency, error_rate
    FROM PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_TEST_RESULTS
        SELECT suite_run_id FROM PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_TEST_SUITE_RUNS
      || '<h1 style="margin:0 0 4px;font-size:22px;font-weight:700;color:#FFFFFF;letter-spacing:-0.3px;">Cortex AI Observability Platform</h1>'
      || '<p style="margin:0;font-size:24px;font-weight:800;color:#29B5E8;">' || avg_latency::STRING || '<span style="font-size:14px;color:#6B7280;">ms</span></p>'
      || '<p style="margin:4px 0 0;font-size:11px;color:#6B7280;">Avg Latency</p></td></tr></table></td>'
      || '<p style="margin:4px 0 0;font-size:11px;color:#6B7280;">Error Rate</p></td></tr></table></td>'
      || '<p style="margin:4px 0 0;font-size:11px;color:#6B7280;">Monitoring Views</p></td></tr></table></td>'
      || '<td><p style="margin:0;font-size:14px;color:#374151;">P95 Latency SLA (&lt; 1500ms)</p></td>'
      || '<td><p style="margin:0;font-size:14px;color:#374151;">P99 Latency SLA (&lt; 3000ms)</p></td>'
      || '<td><p style="margin:0;font-size:14px;color:#374151;">Error Rate SLA (&lt; 1%)</p></td>'
      || '<tr><td width="50%" style="padding:6px 0;"><span style="color:#059669;font-weight:700;">&#10003;</span> <span style="font-size:13px;color:#374151;">' || view_count::STRING || ' Monitoring Views</span></td>'
        'Cortex AI Observability - CXO Executive Report | ' || TO_CHAR(CURRENT_DATE(), 'Mon DD, YYYY'),
      'P95 latency exceeded 3000ms in the last 5 minutes.'
      'Error rate exceeded 5% in the last 5 minutes.'
      'The monitoring pipeline has stopped receiving events.'
      (metric_date, service_name, user_name, role_name, total_requests, avg_latency_ms, p50_latency_ms, p95_latency_ms, p99_latency_ms, max_latency_ms, error_count, error_rate_pct, unique_queries)
      CURRENT_DATE() - 1 AS metric_date,
      RECORD_ATTRIBUTES['snow.ai.observability.object.name']::STRING AS service_name,
      RECORD_ATTRIBUTES['snow.ai.observability.user.name']::STRING AS user_name,
      RECORD_ATTRIBUTES['snow.ai.observability.role.name']::STRING AS role_name,
      ROUND(AVG(TRY_TO_NUMBER(VALUE['snow.ai.observability.response_time_ms']::STRING)), 2),
      ROUND(PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY TRY_TO_NUMBER(VALUE['snow.ai.observability.response_time_ms']::STRING)), 2),
      ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY TRY_TO_NUMBER(VALUE['snow.ai.observability.response_time_ms']::STRING)), 2),
      ROUND(PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY TRY_TO_NUMBER(VALUE['snow.ai.observability.response_time_ms']::STRING)), 2),
      MAX(TRY_TO_NUMBER(VALUE['snow.ai.observability.response_time_ms']::STRING)),
      COUNT_IF(TRY_TO_NUMBER(VALUE['snow.ai.observability.response_status_code']::STRING) != 200),
      ROUND(100.0 * COUNT_IF(TRY_TO_NUMBER(VALUE['snow.ai.observability.response_status_code']::STRING) != 200) / NULLIF(COUNT(*), 0), 2),
      COUNT(DISTINCT VALUE['snow.ai.observability.request_body']['query']::STRING)
CREATE OR REPLACE TABLE PRD_CORTEX_OBSERVABILITY.LIVE_TEST.TBL_KNOWLEDGE_BASE (
INSERT INTO PRD_CORTEX_OBSERVABILITY.LIVE_TEST.TBL_KNOWLEDGE_BASE (title, content, category) VALUES
    ('Query Acceleration', 'Query Acceleration Service offloads portions of eligible queries to shared compute to reduce latency.', 'PERFORMANCE'),
--     FROM PRD_CORTEX_OBSERVABILITY.LIVE_TEST.TBL_KNOWLEDGE_BASE
CREATE OR REPLACE TASK PRD_CORTEX_OBSERVABILITY.MONITORING.TSK_WEEKLY_CXO_REPORT
  CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_SEND_CXO_REPORT('skrz2014@gmail.com');
ALTER TASK PRD_CORTEX_OBSERVABILITY.MONITORING.TSK_WEEKLY_CXO_REPORT RESUME;
--   ALT_SPIKE_LATENCY               - 5-min P95 > 3000ms
--   ALT_SPIKE_ERROR_RATE            - 5-min error rate > 5%
-- ║ ⚠️  CRITICAL: ACCOUNT_USAGE LATENCY REFERENCE                                ║
-- ║  • DO NOT use for real-time dashboards or alerts                              ║
-- 16A. EVENT LATENCY BUFFER VIEW (3-MINUTE PROPAGATION SAFETY)
CREATE OR REPLACE TABLE PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_ALERT_STATE (
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_FIRE_ALERT(
        FROM PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_ALERT_STATE
        MERGE INTO PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_ALERT_STATE t
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_RESOLVE_ALERT(alert_name STRING)
    UPDATE PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_ALERT_STATE
-- 16C. HYBRID SEARCH QUALITY METRICS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SEARCH_QUALITY_METRICS AS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_ERROR_CLASSIFICATION AS
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_NEW_EVENT_FIELDS AS
CREATE OR REPLACE ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_COST_THRESHOLD
    FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_DAILY_OBSERVABILITY_COSTS
    CALL PRD_CORTEX_OBSERVABILITY.MONITORING.SP_FIRE_ALERT(
      'ALERT: Daily Observability Cost Exceeded $30',
      'PRD_CORTEX_OBS_XS_WH has consumed >10 credits today. Review VW_DAILY_OBSERVABILITY_COSTS.'
ALTER ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_COST_THRESHOLD RESUME;
CREATE OR REPLACE TABLE PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TBL_SLA_DEFINITIONS_HISTORY (
    sla_metric STRING,
CREATE OR REPLACE STREAM PRD_CORTEX_OBSERVABILITY.MONITORING.STR_SLA_CHANGES
  ON TABLE PRD_CORTEX_OBSERVABILITY.MONITORING.TBL_SLA_DEFINITIONS
CREATE OR REPLACE TASK PRD_CORTEX_OBSERVABILITY.MONITORING.TSK_TRACK_SLA_CHANGES
  WHEN SYSTEM$STREAM_HAS_DATA('PRD_CORTEX_OBSERVABILITY.MONITORING.STR_SLA_CHANGES')
  INSERT INTO PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TBL_SLA_DEFINITIONS_HISTORY
    (action, service_name, sla_metric, new_threshold, new_severity)
    SLA_METRIC,
  FROM PRD_CORTEX_OBSERVABILITY.MONITORING.STR_SLA_CHANGES;
ALTER TASK PRD_CORTEX_OBSERVABILITY.MONITORING.TSK_TRACK_SLA_CHANGES RESUME;
CREATE OR REPLACE FUNCTION PRD_CORTEX_OBSERVABILITY.GOVERNANCE.REDACT_SENSITIVE_QUERY_V2(query_text STRING)
--   PRD_CORTEX_OBSERVABILITY.MONITORING.AD_VOLUME_ANOMALIES(
--     INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'PRD_CORTEX_OBSERVABILITY.MONITORING.VW_DAILY_TRENDS'),
--   PRD_CORTEX_OBSERVABILITY.MONITORING.FCAST_DAILY_REQUESTS(
--   VW_SEARCH_QUALITY_METRICS      - Hybrid search effectiveness
CREATE OR REPLACE DYNAMIC TABLE PRD_CORTEX_OBSERVABILITY.AGGREGATED.DT_HOURLY_METRICS
CREATE OR REPLACE DYNAMIC TABLE PRD_CORTEX_OBSERVABILITY.AGGREGATED.DT_DAILY_SERVICE_SUMMARY
    ROUND(AVG(avg_latency_ms), 2) AS avg_latency_ms,
FROM PRD_CORTEX_OBSERVABILITY.AGGREGATED.DT_HOURLY_METRICS
ALTER TABLE PRD_CORTEX_OBSERVABILITY.AGGREGATED.TBL_DAILY_SEARCH_METRICS
  CLUSTER BY (metric_date, service_name);
CREATE OR REPLACE ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_NO_EVENTS_30MIN
ALTER ALERT PRD_CORTEX_OBSERVABILITY.MONITORING.ALT_NO_EVENTS_30MIN RESUME;
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.MONITORING.VW_OBJECT_INVENTORY AS
WHERE TABLE_CATALOG = 'PRD_CORTEX_OBSERVABILITY'
WHERE PROCEDURE_CATALOG = 'PRD_CORTEX_OBSERVABILITY'
WHERE FUNCTION_CATALOG = 'PRD_CORTEX_OBSERVABILITY';
CREATE TAG IF NOT EXISTS PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TAG_DOMAIN
  ALLOWED_VALUES = 'AI_OBSERVABILITY', 'SECURITY', 'COST', 'REPORTING';
CREATE TAG IF NOT EXISTS PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TAG_SENSITIVITY
CREATE TAG IF NOT EXISTS PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TAG_COST_CENTER
  PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TAG_DOMAIN = 'AI_OBSERVABILITY';
  PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TAG_COST_CENTER = 'AI_PLATFORM';
  PRD_CORTEX_OBSERVABILITY.GOVERNANCE.TAG_SENSITIVITY = 'CONFIDENTIAL';
CREATE OR REPLACE PROCEDURE PRD_CORTEX_OBSERVABILITY.MONITORING.SP_SET_SESSION_TAGS()
    ALTER SESSION SET QUERY_TAG = 'cortex_observability';
    RETURN 'Session tagged: cortex_observability';
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.REPORTING.VW_EXEC_WEEKLY_SUMMARY AS
FROM PRD_CORTEX_OBSERVABILITY.AGGREGATED.DT_DAILY_SERVICE_SUMMARY
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.REPORTING.VW_COST_SHOWBACK AS
FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_COST_BY_USER r
CREATE OR REPLACE VIEW PRD_CORTEX_OBSERVABILITY.REPORTING.VW_PLATFORM_HEALTH_SCORE AS
    (SELECT pass_rate_pct FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_TEST_SUITE_SUMMARY LIMIT 1) AS test_pass_rate,
    (SELECT COUNT(DISTINCT service_name) FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_SERVICE_REGISTRY WHERE service_status = 'ACTIVE') AS active_services,
    (SELECT COUNT(*) FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_PIPELINE_HEALTH WHERE pipeline_status = 'HEALTHY') AS healthy_pipelines,
    (SELECT COUNT(*) FROM PRD_CORTEX_OBSERVABILITY.MONITORING.VW_PIPELINE_HEALTH) AS total_pipelines,
--   DT_HOURLY_METRICS              - 5-min lag, auto-incremental hourly rollups
--   TAG_DOMAIN                     - AI_OBSERVABILITY, SECURITY, COST, REPORTING
--   TBL_DAILY_SEARCH_METRICS       - Clustered on (metric_date, service_name)