-- ============================================================================
-- 10_cxo_report.sql
-- Deterministic modular extraction
-- Guarantees:
--   ✔ Zero skipped statements
--   ✔ No duplicate SQL within file
--   ✔ Ordered deployment sequence
-- ============================================================================

-- ║ 1. EXECUTIVE SUMMARY (CTO/CFO VIEW)                                        ║
-- 2. AGGREGATION-FIRST REPORTING:
      || '<p style="margin:0;font-size:14px;color:#A3BFDB;">CXO Executive Status Report</p>'
      || '<p style="margin:0;font-size:11px;color:#7EC8E3;text-transform:uppercase;letter-spacing:0.5px;">Report Date</p>'
      || '<h2 style="margin:0 0 16px;font-size:14px;font-weight:700;color:#0F2A44;text-transform:uppercase;letter-spacing:0.5px;">Executive Summary</h2>'
      || '<td><p style="margin:0;font-size:12px;color:#A3BFDB;">Generated by <strong style="color:#29B5E8;">SP_SEND_CXO_REPORT()</strong></p>'
-- 15F. SCHEDULED CXO REPORT (WEEKLY MONDAY 8 AM UTC)
--   TSK_WEEKLY_CXO_REPORT           - Monday 8 AM UTC exec report
-- ║  • Use for daily reconciliation and monthly reporting ONLY                    ║
-- NEW Views (REPORTING):
--   REPORTING                       - BI-optimized executive views

-- =====================================================================
-- UNMATCHED CARRY-FORWARD LINES (NO SKIPPED STATEMENTS)
-- ============================================================================
-- Date: 2026-05-04
-- NAMING CONVENTION:
--   Role:         FR_<DOMAIN>_<ACCESS_LEVEL>    (e.g. FR_CORTEX_OBS_READONLY)
--   Task:         TSK_<FREQUENCY>_<ACTION>      (e.g. TSK_DAILY_AGGREGATION)
-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ╚══════════════════════════════════════════════════════════════════════════════╝
--
-- BUSINESS VALUE:
--   • Full visibility into AI-powered search usage across the enterprise
--   • Compliance/audit trail for all search queries (regulatory requirement)
-- RISK MITIGATION:
--   • Eliminates compliance gap: all queries logged and auditable
--   • Detects anomalous usage patterns (potential data exfiltration)
--   • Provides evidence for regulatory audits (SOC2, GDPR, HIPAA)
--   • Identifies optimization opportunities (underused/overused services)
-- AI GOVERNANCE MATURITY:
--   • Establishes foundation for AI operations (AIOps) practices
-- ║ 2. REFERENCE ARCHITECTURE                                                   ║
-- ┌─────────────────────────────────────────────────────────────────────────┐
-- │                        APPLICATION LAYER                                 │
-- └────────────────────────────────┬────────────────────────────────────────┘
--                                  │
-- ┌────────────────────────────────▼────────────────────────────────────────┐
-- │   (Services with REQUEST_LOGGING = TRUE)                                 │
--                                  │ (automatic event emission)
-- │   • Curated views (performance, usage, errors)                           │
-- │   • Aggregated summary tables (daily/hourly)                             │
-- └───────────┬────────────────────┬────────────────────────────────────────┘
--             │                    │
-- ┌───────────▼──────────┐  ┌─────▼──────────────────────────────────────┐
-- │    integrations      │  │  • External: Datadog, Splunk, Grafana      │
-- └──────────────────────┘  └────────────────────────────────────────────┘
-- ║ 3. IMPLEMENTATION PLAN                                                      ║
-- ═══════════════════════════════════════════════════════════════════════════════
--   SET REQUEST_LOGGING = TRUE;
-- For new services, include at creation time:
--   ON <column>
--   TARGET_LAG = '1 hour'
--   REQUEST_LOGGING = TRUE
--   AS (SELECT ... FROM ...);
USE ROLE ACCOUNTADMIN;
-- Intended for: Platform engineers, SRE team, BI analysts.
-- Intended for: Security team, AI governance leads, compliance officers.
--   TO ROLE FR_CORTEX_OBS_READONLY;
-- Role hierarchy: FR_CORTEX_OBS_ADMIN inherits all privileges of FR_CORTEX_OBS_READONLY
-- Attach FR_CORTEX_OBS_ADMIN into the standard Snowflake role hierarchy under SYSADMIN
-- Isolated from production workloads to prevent resource contention.
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
-- Grants: Least-privilege access for FR_CORTEX_OBS_READONLY
SELECT
    TIMESTAMP                                                                          AS event_timestamp,
    VALUE                                                                               AS raw_event
WHERE TIMESTAMP >= DATEADD('day', -7, CURRENT_TIMESTAMP())
-- Use case: Identify performance degradation, capacity planning, query optimization.
    event_timestamp,
    service_name,
    user_name,
    role_name,
    query_text,
    response_time_ms,
    result_limit
WHERE response_time_ms > 2000
ORDER BY response_time_ms DESC;
-- VW_FAILED_REQUESTS: Captures all non-200 responses (client errors, server errors).
-- Use case: Detect malformed requests, service outages, permission issues.
-- Common causes: Invalid column references, malformed filters, empty queries.
    status_code
WHERE status_code != 200
ORDER BY event_timestamp DESC;
-- Use case: Identify power users, detect abuse, support capacity planning.
    COUNT(*)                            AS total_requests,
    COUNT_IF(status_code != 200)        AS error_count,
    MIN(event_timestamp)                AS first_request,
    MAX(event_timestamp)                AS last_request
GROUP BY user_name, role_name
ORDER BY total_requests DESC;
    DATE_TRUNC('hour', event_timestamp)  AS hour_bucket,
    COUNT(*)                             AS request_count,
    COUNT_IF(status_code != 200)         AS error_count,
    ROUND(COUNT_IF(status_code != 200) / COUNT(*) * 100, 2) AS error_rate_pct
GROUP BY service_name, hour_bucket
ORDER BY hour_bucket DESC, service_name;
-- VW_DAILY_TRENDS: Daily aggregated request counts, unique users, and error totals.
    DATE_TRUNC('day', event_timestamp)   AS day_bucket,
    COUNT(*)                             AS daily_requests,
    COUNT(DISTINCT user_name)            AS unique_users,
    COUNT_IF(status_code != 200)         AS daily_errors
GROUP BY service_name, day_bucket
ORDER BY day_bucket DESC;
-- Severity levels: 'warning' (notify), 'critical' (page on-call), 'info' (log only).
    service_name         STRING,
    severity             STRING,
    created_at           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
VALUES
    ('product_search', 'error_rate_pct', 1.0, 'critical'),
    ('knowledge_base_search', 'error_rate_pct', 2.0, 'critical');
    SELECT
        service_name,
        ROUND(COUNT_IF(status_code != 200) / NULLIF(COUNT(*), 0) * 100, 2) AS error_rate_pct
    WHERE event_timestamp >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
    GROUP BY service_name
)
    s.service_name,
    s.severity,
        WHEN 'error_rate_pct' THEN m.error_rate_pct
    END AS current_value,
    CASE
                WHEN 'error_rate_pct' THEN m.error_rate_pct
        ELSE 'COMPLIANT'
    SERVICE_NAME                         AS service_name,
    CONSUMPTION_TYPE,
    MODEL_NAME                           AS embedding_model,
    TRY_TO_NUMBER(TOKENS)               AS token_count
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_SEARCH_DAILY_USAGE_HISTORY
WHERE USAGE_DATE >= DATEADD('year', -1, CURRENT_TIMESTAMP())
WITH user_daily_requests AS (
        user_name,
        role_name,
        DATE_TRUNC('day', event_timestamp)::DATE AS usage_date,
        COUNT(*) AS request_count
    GROUP BY user_name, role_name, service_name, usage_date
),
daily_totals AS (
        usage_date,
        SUM(request_count) AS total_daily_requests
    FROM user_daily_requests
    GROUP BY service_name, usage_date
        SERVICE_NAME AS service_name,
    FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_SEARCH_DAILY_USAGE_HISTORY
    WHERE USAGE_DATE >= DATEADD('month', -3, CURRENT_TIMESTAMP())
    u.user_name,
    u.role_name,
    u.service_name,
    u.usage_date,
    u.request_count,
    dt.total_daily_requests,
    ROUND(u.request_count * 100.0 / NULLIF(dt.total_daily_requests, 0), 2) AS pct_of_daily_traffic,
FROM user_daily_requests u
JOIN daily_totals dt ON u.service_name = dt.service_name AND u.usage_date = dt.usage_date
-- Breaks down by consumption type: SERVING, EMBED_TEXT_TOKENS, BATCH.
WITH actual_monthly AS (
        DATE_TRUNC('month', USAGE_DATE)::DATE AS usage_month,
        CONSUMPTION_TYPE,
        SUM(TRY_TO_NUMBER(TOKENS)) AS total_tokens
    WHERE USAGE_DATE >= DATEADD('year', -1, CURRENT_TIMESTAMP())
    GROUP BY service_name, usage_month, CONSUMPTION_TYPE
request_counts AS (
        DATE_TRUNC('month', event_timestamp)::DATE AS usage_month,
        COUNT(*) AS monthly_requests,
        COUNT(DISTINCT user_name) AS unique_users
    GROUP BY service_name, usage_month
    COALESCE(a.service_name, r.service_name) AS service_name,
    COALESCE(a.usage_month, r.usage_month) AS usage_month,
    r.monthly_requests,
    r.unique_users,
    SUM(a.total_tokens) AS total_tokens_consumed,
FROM actual_monthly a
FULL OUTER JOIN request_counts r ON a.service_name = r.service_name AND a.usage_month = r.usage_month
GROUP BY COALESCE(a.service_name, r.service_name), COALESCE(a.usage_month, r.usage_month),
         r.monthly_requests, r.unique_users
WITH role_weekly_requests AS (
        DATE_TRUNC('week', event_timestamp)::DATE AS usage_week,
        COUNT(*) AS weekly_requests
    GROUP BY role_name, service_name, usage_week
weekly_totals AS (
        usage_week,
        SUM(weekly_requests) AS total_weekly_requests
    FROM role_weekly_requests
    GROUP BY service_name, usage_week
        DATE_TRUNC('week', USAGE_DATE)::DATE AS usage_week,
    r.role_name,
    r.service_name,
    r.usage_week,
    r.weekly_requests,
    wt.total_weekly_requests,
    ROUND(r.weekly_requests * 100.0 / NULLIF(wt.total_weekly_requests, 0), 2) AS pct_of_weekly_traffic,
FROM role_weekly_requests r
JOIN weekly_totals wt ON r.service_name = wt.service_name AND r.usage_week = wt.usage_week
-- Source: CORTEX_SEARCH_SERVING_USAGE_HISTORY (hourly resolution).
    START_TIME,
    END_TIME,
    SERVICE_NAME AS service_name,
    SERVICE_ID
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_SEARCH_SERVING_USAGE_HISTORY
WHERE START_TIME >= DATEADD('month', -1, CURRENT_TIMESTAMP())
ORDER BY START_TIME DESC;
-- Add team DLs here for production: platform-team@company.com, ai-ops@company.com
  ALLOWED_RECIPIENTS = ('skrz2014@gmail.com');
-- Evaluation: Every 5 minutes. Groups by service to identify which service is degraded.
  SCHEDULE = '5 MINUTE'
  IF (EXISTS (
    SELECT 1
    WHERE TIMESTAMP >= DATEADD('minute', -15, CURRENT_TIMESTAMP())
  ))
  THEN
      'skrz2014@gmail.com',
    );
-- Evaluation: Every 5 minutes over a 10-minute sliding window.
    WHERE TIMESTAMP >= DATEADD('minute', -10, CURRENT_TIMESTAMP())
    HAVING COUNT(*) > 10
-- ALT_SPIKE_VOLUME: Fires when current hour traffic exceeds 3x the 7-day hourly average.
-- Evaluation: Every 30 minutes. Baseline excludes last 24h to avoid self-referencing spikes.
-- Response: Identify source user/role, check for automated retry loops.
  SCHEDULE = '30 MINUTE'
    WITH baseline AS (
        SELECT COUNT(*) / 24 AS avg_hourly_requests
        WHERE TIMESTAMP >= DATEADD('day', -7, CURRENT_TIMESTAMP())
          AND TIMESTAMP < DATEADD('day', -1, CURRENT_TIMESTAMP())
    ),
    current_hour AS (
        SELECT COUNT(*) AS current_requests
        WHERE TIMESTAMP >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
    )
    FROM current_hour, baseline
    WHERE current_requests > avg_hourly_requests * 3
      'Query volume in the last hour is 3x above the 7-day average. Possible anomaly.'
-- 3H. DATA RETENTION STRATEGY
-- Retention: 2 years (managed by TSK_MONTHLY_RETENTION_CLEANUP).
-- Ingestion: Populated nightly at 01:00 UTC by TSK_DAILY_AGGREGATION.
-- Storage estimate: ~1 row per user/service/day; <100MB/month typical.
    user_name            STRING,
    role_name            STRING,
    total_requests       NUMBER,
    error_count          NUMBER,
    error_rate_pct       FLOAT,
    unique_queries       NUMBER,
    ingested_at          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
-- TSK_DAILY_AGGREGATION: Nightly ETL that rolls up yesterday's raw events into
-- Reads directly from event table (not the 7-day view) for precise date boundaries.
  SCHEDULE = 'USING CRON 0 1 * * * UTC'
AS
    COUNT(*)                                                                               AS total_requests,
WHERE TIMESTAMP >= DATEADD('day', -1, DATE_TRUNC('day', CURRENT_TIMESTAMP()))
  AND TIMESTAMP < DATE_TRUNC('day', CURRENT_TIMESTAMP())
GROUP BY service_name, user_name, role_name;
-- TSK_MONTHLY_RETENTION_CLEANUP: Purges aggregated data older than 2 years.
-- Adjust DATEADD interval to match your organization's data retention policy.
-- Note: Raw event table retention is managed separately by Snowflake (default 14 days).
  SCHEDULE = 'USING CRON 0 3 1 * * UTC'
-- For Datadog/Splunk: Use external functions or Snowflake's Kafka connector
-- Example: Create a secure share for external BI tools
-- ║ 4. SAMPLE ANALYTICS QUERIES                                                 ║
-- SAMPLE QUERY 1: Top 20 most frequent search queries (last 24 hours)
-- Use case: Understand what users are searching for most. Informs content gaps.
    COUNT(*) AS frequency,
WHERE TIMESTAMP >= DATEADD('day', -1, CURRENT_TIMESTAMP())
GROUP BY query_text
ORDER BY frequency DESC
LIMIT 20;
-- Use case: Identify performance outliers for targeted optimization.
-- Look for: Large result limits, complex filter expressions, low-selectivity queries.
    TIMESTAMP AS event_time,
LIMIT 25;
-- SAMPLE QUERY 3: Error breakdown by service (last 7 days)
-- Use case: Identify systematic failures across services.
-- Common status codes: 400 (bad request), 429 (rate limited), 500 (internal error).
    COUNT(*) AS occurrences
GROUP BY service, status_code
ORDER BY occurrences DESC;
-- SAMPLE QUERY 4: Hourly request volume trend (last 7 days)
-- Use case: Capacity planning, identify peak usage hours, detect traffic anomalies.
-- Visualize in Snowsight as a line chart with service as the series dimension.
    DATE_TRUNC('hour', TIMESTAMP) AS hour_bucket,
    COUNT(*) AS requests
GROUP BY hour_bucket, service
ORDER BY hour_bucket DESC;
-- ║ 5. GOVERNANCE & SECURITY                                                    ║
-- FR_CORTEX_OBS_ADMIN / ACCOUNTADMIN: See full query text (for incident investigation).
-- FR_CORTEX_OBS_READONLY: Sees first 10 characters + redaction marker (enough for pattern ID).
-- All other roles: Fully masked (zero visibility into search content).
  AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('FR_CORTEX_OBS_ADMIN', 'ACCOUNTADMIN') THEN val
    WHEN CURRENT_ROLE() IN ('FR_CORTEX_OBS_READONLY') THEN
    ELSE '***MASKED***'
  END;
-- Apply to views that expose query text (applied on underlying table/view columns)
-- RAP_TENANT_ISOLATION: Enforces multi-tenant row-level isolation.
-- Admins see all rows. Other roles only see rows matching their role_name.
  AS (row_role_name STRING) RETURNS BOOLEAN ->
  CURRENT_ROLE() IN ('FR_CORTEX_OBS_ADMIN', 'ACCOUNTADMIN')
  OR CURRENT_ROLE() = row_role_name;
-- Apply to tenant-scoped views:
-- Joins ACCESS_HISTORY with QUERY_HISTORY to get role and SQL text context.
-- Use case: Audit trail for SOC2/HIPAA compliance, detect unauthorized access.
    ah.query_start_time,
    ah.user_name,
    qh.role_name,
    qh.query_text,
    ah.direct_objects_accessed
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY ah
JOIN SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY qh
  ON ah.query_id = qh.query_id
    TRANSFORM(ah.direct_objects_accessed, o -> o:"objectName"::STRING))
ORDER BY ah.query_start_time DESC;
--   • Event table: ~1KB per event; 1M requests/day ~ 1GB/day ~ 30GB/month
--   • Aggregated tables: minimal (<100MB/month)
--   • Recommendation: Set event table retention to 90 days max
--   • Raw event queries: Use PRD_CORTEX_OBS_XS_WH for ad-hoc
-- OPTIMIZATION STRATEGIES:
--   • Use time-bounded queries with TIMESTAMP filters
--   • Schedule intensive analytics during off-peak hours
-- ║ 7. PRODUCTION BEST PRACTICES                                                ║
--    • Use pre-aggregated tables (daily/hourly) for BI tools
--    • Reserve raw queries for incident investigation only
-- 3. AUTOMATED PIPELINES:
--    • Use TASKs for daily aggregation (not manual queries)
--    • Automate retention/cleanup with scheduled tasks
-- 4. SEPARATION OF CONCERNS:
-- ║ 8. RISKS & MITIGATIONS                                                      ║
-- ┌────────────────────────────┬──────────────────────────────────────────────┐
-- │ RISK                       │ MITIGATION                                   │
-- ├────────────────────────────┼──────────────────────────────────────────────┤
-- │ High log volume            │ 90-day retention + daily aggregation         │
-- └────────────────────────────┴──────────────────────────────────────────────┘
-- ║ 9. MATURITY ROADMAP                                                         ║
-- LEVEL 1 - BASIC LOGGING (Week 1-2):
--   * Verify data flowing into event table
--   * Connect BI tools (Power BI / Tableau)
--   * Create incident response runbooks
--   * Optimize underperforming services
-- LEVEL 5 - AI-DRIVEN ANOMALY DETECTION (Week 9-12):
--   * Deploy Snowflake ML-based anomaly detection on usage patterns
--   * Predictive capacity planning
--   * Automated service scaling recommendations
--   * Continuous improvement feedback loop
-- OBJECT INVENTORY (Production Names)
-- Roles:         FR_CORTEX_OBS_READONLY | FR_CORTEX_OBS_ADMIN
--   VW_FAILED_REQUESTS        - Non-200 status codes
--   VW_TOP_USERS              - User activity ranking
--   VW_DAILY_TRENDS           - Daily aggregated trends
-- Tables:
-- Tasks:
--   TSK_DAILY_AGGREGATION         - Daily rollup at 01:00 UTC
--   TSK_MONTHLY_RETENTION_CLEANUP - Purge data > 2 years
--   ALT_SPIKE_VOLUME         - 3x hourly average (30 min check)
-- Policies (GOVERNANCE):
-- END OF IMPLEMENTATION BLUEPRINT
-- ║ 10. PRODUCTION HARDENING IMPROVEMENTS                                        ║
RETURNS BOOLEAN
LANGUAGE SQL
$$
DECLARE
    start_time TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
    current_count INT := 0;
BEGIN
    WHILE (current_count < expected_count AND DATEDIFF('minute', start_time, CURRENT_TIMESTAMP()) < 5) DO
        CALL SYSTEM$WAIT(30);
        SELECT COUNT(*) INTO current_count
        WHERE TIMESTAMP >= DATEADD('minute', -10, CURRENT_TIMESTAMP());
    END WHILE;
    RETURN current_count >= expected_count;
END;
$$;
RETURNS TABLE (check_name STRING, status STRING, message STRING)
    res RESULTSET;
    res := (
        SELECT 'EVENT_TABLE_ACCESS' AS check_name,
                    THEN 'PASS' ELSE 'FAIL' END AS status,
               'Event table accessible' AS message
        UNION ALL
        SELECT 'REQUIRED_PRIVILEGES' AS check_name,
               CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'FR_CORTEX_OBS_ADMIN')
               'Run as ACCOUNTADMIN or FR_CORTEX_OBS_ADMIN' AS message
                    THEN 'PASS' ELSE 'WARNING' END AS status,
    RETURN TABLE(res);
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 75 PERCENT DO NOTIFY
    ON 90 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND;
    DATE_TRUNC('day', START_TIME) AS usage_date,
  AND START_TIME >= DATEADD('month', -1, CURRENT_TIMESTAMP())
ORDER BY usage_date DESC;
-- 10E. [HIGH] QUERY FINGERPRINTING FOR DE-DUPLICATION
RETURNS STRING
    UPPER(REGEXP_REPLACE(
        REGEXP_REPLACE(
            REGEXP_REPLACE(
                REGEXP_REPLACE(query_text, '"[^"]*"', '<STRING>'),
                '''[^'']*''', '<STRING>'),
            '\\d+', '<NUM>'),
        '\\s+', ' '
    ))
    *,
-- 10F. [MEDIUM] VOLUME FORECASTING & CAPACITY PLANNING
WITH daily_stats AS (
        DATE_TRUNC('day', event_timestamp) AS day,
        COUNT(*) AS daily_requests
    WHERE event_timestamp >= DATEADD('month', -3, CURRENT_TIMESTAMP())
    GROUP BY day
trend AS (
        REGR_INTERCEPT(daily_requests, DATEDIFF('day', (SELECT MIN(day) FROM daily_stats), day)) AS base_volume
    FROM daily_stats
    CURRENT_DATE() + offset AS forecast_date,
FROM trend, LATERAL FLATTEN(INPUT => ARRAY_GENERATE_RANGE(1, 31)) AS t(offset)
ORDER BY forecast_date;
-- 10G. [MEDIUM] STATISTICAL ANOMALY DETECTION
WITH hourly_baseline AS (
        hour_of_day,
        AVG(hourly_count) AS avg_volume,
        STDDEV(hourly_count) AS stddev_volume
    FROM (
        SELECT
            service_name,
            DATE_TRUNC('hour', event_timestamp) AS hour_bucket,
            HOUR(event_timestamp) AS hour_of_day,
            COUNT(*) AS hourly_count
        WHERE event_timestamp >= DATEADD('day', -30, CURRENT_TIMESTAMP())
          AND event_timestamp < DATEADD('hour', -1, CURRENT_TIMESTAMP())
        GROUP BY service_name, hour_bucket, hour_of_day
    GROUP BY service_name, hour_of_day
current_hourly AS (
        HOUR(event_timestamp) AS hour_of_day,
        COUNT(*) AS current_volume
    c.service_name,
    c.current_volume,
    b.avg_volume,
    b.stddev_volume,
        WHEN b.stddev_volume = 0 OR b.stddev_volume IS NULL THEN 'INSUFFICIENT_DATA'
        WHEN ABS(c.current_volume - b.avg_volume) > (3 * b.stddev_volume) THEN 'ANOMALY'
        WHEN ABS(c.current_volume - b.avg_volume) > (2 * b.stddev_volume) THEN 'WARNING'
        ELSE 'NORMAL'
    END AS anomaly_status
FROM current_hourly c
LEFT JOIN hourly_baseline b ON c.service_name = b.service_name AND c.hour_of_day = b.hour_of_day;
    query_name STRING,
    sql_text STRING,
    refresh_rate_minutes INT,
    created_by STRING,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
     60, 'SYSTEM'),
     5, 'SYSTEM'),
     1440, 'SYSTEM');
WITH event_stats AS (
        DATE_TRUNC('hour', TIMESTAMP) AS hour_bucket,
        COUNT(*) AS total_events,
    WHERE TIMESTAMP >= DATEADD('day', -1, CURRENT_TIMESTAMP())
    GROUP BY hour_bucket
    hour_bucket,
    total_events,
    search_events,
    ROUND(100.0 * search_events / NULLIF(total_events, 0), 2) AS pct_valid_events,
    null_service_name,
    null_status_code,
        WHEN null_service_name > total_events * 0.05 THEN 'FAIL'
        ELSE 'PASS'
    END AS data_quality_status
FROM event_stats
-- UPDATED OBJECT INVENTORY (with new objects from Section 10)
-- NEW Procedures:
--   WAIT_FOR_EVENTS                    - Wait for event propagation (2-5 min)
-- NEW Functions:
--   NORMALIZE_QUERY                    - Query fingerprinting/dedup
--   VW_SEARCH_WITH_FINGERPRINTS        - Queries with dedup fingerprints
--   VW_VOLUME_FORECAST                 - 30-day request volume forecast
--   VW_ANOMALY_DETECTION               - Statistical anomaly detection
-- NEW Tables:
-- END OF PRODUCTION HARDENING IMPROVEMENTS
-- ║ 11. ELITE-TIER ENTERPRISE ENHANCEMENTS                                       ║
-- 11A. END-TO-END REQUEST TRACEABILITY
    TIMESTAMP                                                                            AS event_timestamp,
    VALUE                                                                                AS raw_event
    COUNT(*) AS total_requests,
    COUNT_IF(result_limit = 0 OR status_code != 200) AS zero_result_count,
    COUNT(DISTINCT user_name) AS unique_users,
    ROUND(100.0 * zero_result_count / NULLIF(total_requests, 0), 2) AS zero_result_pct,
        WHEN zero_result_pct > 50 THEN 'POOR'
        WHEN zero_result_pct > 20 THEN 'NEEDS_IMPROVEMENT'
        ELSE 'GOOD'
    END AS quality_rating
WHERE query_text != 'NULL_QUERY'
ORDER BY zero_result_count DESC;
    COUNT(*) AS repeat_count,
    MIN(event_timestamp) AS first_attempt,
    MAX(event_timestamp) AS last_attempt,
    DATEDIFF('second', first_attempt, last_attempt) AS session_duration_sec,
        WHEN repeat_count >= 5 AND session_duration_sec < 300 THEN 'HIGH_FRUSTRATION'
        WHEN repeat_count >= 3 THEN 'MODERATE_FRUSTRATION'
    END AS frustration_level
WHERE event_timestamp >= DATEADD('day', -1, CURRENT_TIMESTAMP())
GROUP BY user_name, query_text
HAVING repeat_count >= 2
ORDER BY repeat_count DESC;
        DATE_TRUNC('hour', START_TIME) AS hour_bucket,
      AND START_TIME >= DATEADD('month', -1, CURRENT_TIMESTAMP())
hourly_requests AS (
        DATE_TRUNC('hour', event_timestamp) AS hour_bucket,
    WHERE event_timestamp >= DATEADD('month', -1, CURRENT_TIMESTAMP())
    GROUP BY hour_bucket, service_name, user_name, role_name
hourly_totals AS (
    SELECT hour_bucket, SUM(request_count) AS total_requests
    FROM hourly_requests
    hr.hour_bucket,
    hr.service_name,
    hr.user_name,
    hr.role_name,
    hr.request_count,
FROM hourly_requests hr
JOIN hourly_totals ht ON hr.hour_bucket = ht.hour_bucket
-- 11D. SENSITIVE DATA DETECTION & PROTECTION IN QUERY TEXT
        WHEN REGEXP_LIKE(query_text, '.*\\d{3}-\\d{2}-\\d{4}.*')        THEN '***SSN_DETECTED***'
        WHEN REGEXP_LIKE(query_text, '.*\\d{4}[- ]?\\d{4}[- ]?\\d{4}[- ]?\\d{4}.*') THEN '***CC_DETECTED***'
        WHEN REGEXP_LIKE(query_text, '.*(password|passwd|pwd|secret|token).*', 'i') THEN '***CREDENTIAL_DETECTED***'
        ELSE query_text
    END
        WHEN REGEXP_LIKE(query_text, '.*\\d{3}-\\d{2}-\\d{4}.*') THEN 'SSN'
        WHEN REGEXP_LIKE(query_text, '.*(password|passwd|pwd|secret|token).*', 'i') THEN 'CREDENTIAL'
        ELSE NULL
    '***REDACTED***' AS redacted_query
WHERE REGEXP_LIKE(query_text, '.*(\\d{3}-\\d{2}-\\d{4}|\\d{4}[- ]?\\d{4}[- ]?\\d{4}[- ]?\\d{4}|password|passwd|pwd|secret|token|[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}).*', 'i');
-- 11E. RATE LIMITING & ABUSE DETECTION
WITH user_rate AS (
        DATE_TRUNC('minute', TIMESTAMP) AS minute_bucket,
        COUNT(*) AS requests_per_minute
    WHERE TIMESTAMP >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
    GROUP BY user_name, role_name, service_name, minute_bucket
    MAX(requests_per_minute) AS peak_rpm,
    AVG(requests_per_minute) AS avg_rpm,
    COUNT(DISTINCT minute_bucket) AS active_minutes,
    SUM(requests_per_minute) AS total_requests_1h,
        WHEN peak_rpm > 100 THEN 'CRITICAL_ABUSE'
        WHEN peak_rpm > 50  THEN 'HIGH_RATE'
        WHEN total_requests_1h > 10000 THEN 'SUSTAINED_HIGH_VOLUME'
    END AS abuse_classification,
        WHEN peak_rpm > 100 THEN 'REVOKE ROLE / SUSPEND USER IMMEDIATELY'
        WHEN total_requests_1h > 10000 THEN 'INVESTIGATE - POTENTIAL BOT / RUNAWAY PIPELINE'
        ELSE 'NO ACTION REQUIRED'
    END AS recommended_action
FROM user_rate
GROUP BY user_name, role_name, service_name
ORDER BY peak_rpm DESC;
  SCHEDULE = '2 MINUTE'
    WHERE abuse_classification IN ('CRITICAL_ABUSE', 'HIGH_RATE')
      'High request rate detected. Check VW_ABUSE_DETECTION for details.'
    DATE_TRUNC('hour', event_timestamp) AS hour_bucket,
    COUNT(*) AS request_count,
    ROUND(PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY response_time_ms), 2) AS p50_ms,
    ROUND(PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY response_time_ms), 2) AS p90_ms,
    ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY response_time_ms), 2) AS p95_ms,
    ROUND(PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY response_time_ms), 2) AS p99_ms,
    COUNT_IF(response_time_ms < 1000) AS fast_count,
        WHEN p95_ms > 3000 THEN 'CRITICAL'
        WHEN p95_ms > 1500 THEN 'DEGRADED'
        WHEN p95_ms > 1000 THEN 'ACCEPTABLE'
        ELSE 'HEALTHY'
WHERE response_time_ms > 0
        WHEN response_time_ms > 5000 THEN 'CRITICAL (>5s)'
        WHEN response_time_ms > 3000 THEN 'HIGH (3-5s)'
        WHEN response_time_ms > 1000 THEN 'MEDIUM (1-3s)'
        WHEN response_time_ms > 500  THEN 'LOW (500ms-1s)'
        ELSE 'FAST (<500ms)'
    query_text
WHERE response_time_ms > 0;
    check_timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    service_name STRING,
    target_lag STRING,
    indexing_state STRING,
    raw_metadata VARIANT
        'service_name' AS service_name,
        'target_lag' AS target_lag,
        'indexing_state' AS indexing_state,
        NULL AS raw_metadata
    FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
    RETURN 'Freshness logged at ' || CURRENT_TIMESTAMP()::STRING;
    check_timestamp,
    target_lag,
    indexing_state,
        WHEN indexing_state != 'ACTIVE' THEN 'STALE'
        ELSE 'FRESH'
    END AS freshness_status
QUALIFY ROW_NUMBER() OVER (PARTITION BY service_name ORDER BY check_timestamp DESC) = 1;
  SCHEDULE = '10 MINUTE'
    WHERE freshness_status = 'STALE'
      'One or more search services have stale indexes. Check VW_FRESHNESS_STATUS.'
    executed_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    expected_outcome STRING,
    actual_outcome STRING,
    passed BOOLEAN,
    details STRING
        COUNT(*) > 0 AS passed,
        'Views should return 0 rows without error' AS expected_outcome,
        'QUERY_SUCCEEDED' AS actual_outcome,
        TRUE AS passed,
        'VW_ANOMALY_DETECTION handles empty data' AS details;
        'DQ view should run without errors' AS expected_outcome,
        'VW_DATA_QUALITY executes successfully' AS details;
        WHERE executed_at >= DATEADD('minute', -1, CURRENT_TIMESTAMP())
        ORDER BY executed_at DESC
-- 11I. MULTI-SERVICE / MULTI-TENANT DYNAMIC DISCOVERY
    MIN(event_timestamp) AS first_seen,
    MAX(event_timestamp) AS last_seen,
    COUNT(DISTINCT role_name) AS unique_roles,
        WHEN last_seen < DATEADD('day', -7, CURRENT_TIMESTAMP()) THEN 'INACTIVE'
        WHEN last_seen < DATEADD('day', -1, CURRENT_TIMESTAMP()) THEN 'LOW_ACTIVITY'
        ELSE 'ACTIVE'
    END AS service_status
WHERE service_name IS NOT NULL
    role_name AS tenant_identifier,
    DATE_TRUNC('day', event_timestamp) AS usage_date,
    COUNT(*) AS daily_requests,
    COUNT(DISTINCT user_name) AS active_users,
    COUNT_IF(status_code != 200) AS error_count,
    ROUND(100.0 * error_count / NULLIF(daily_requests, 0), 2) AS error_rate_pct
WHERE event_timestamp >= DATEADD('month', -1, CURRENT_TIMESTAMP())
GROUP BY tenant_identifier, service_name, usage_date
ORDER BY usage_date DESC, daily_requests DESC;
WITH expected_fields AS (
    SELECT column1 AS field_path, column2 AS expected_type
    FROM VALUES
recent_sample AS (
    SELECT TOP 100 *
    ORDER BY TIMESTAMP DESC
field_presence AS (
        ef.field_path,
        ef.expected_type,
        COUNT_IF(rs.RECORD_ATTRIBUTES[ef.field_path] IS NOT NULL OR rs.VALUE[ef.field_path] IS NOT NULL) AS present_count,
        COUNT(*) AS total_sampled,
        ROUND(100.0 * present_count / NULLIF(total_sampled, 0), 2) AS presence_pct
    FROM expected_fields ef
    CROSS JOIN recent_sample rs
    GROUP BY ef.field_path, ef.expected_type
    field_path,
    expected_type,
    present_count,
    total_sampled,
    presence_pct,
        WHEN presence_pct = 0 THEN 'MISSING'
        WHEN presence_pct < 50 THEN 'DEGRADED'
        WHEN presence_pct < 95 THEN 'PARTIAL'
    END AS drift_status
FROM field_presence
ORDER BY presence_pct ASC;
-- 11K. MATERIALIZED VIEWS FOR SCALE (HIGH-VOLUME OPTIMIZATION)
GROUP BY hour_bucket, service_name;
    DATE_TRUNC('day', TIMESTAMP) AS day_bucket,
GROUP BY day_bucket, service_name, user_name;
    'Total search requests in last 7 days' AS description
UNION ALL
    'ERROR_RATE_24H',
    ROUND(100.0 * COUNT_IF(status_code != 200) / NULLIF(COUNT(*), 0), 2)::STRING,
    ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY response_time_ms), 0)::STRING,
  AND response_time_ms > 0
    'UNIQUE_USERS_7D',
    COUNT(DISTINCT user_name)::STRING,
    'Unique users in last 7 days'
    'ACTIVE_SERVICES',
    COUNT(DISTINCT service_name)::STRING,
WHERE event_timestamp >= DATEADD('day', -1, CURRENT_TIMESTAMP());
    DATE_TRUNC('week', event_timestamp) AS week_start,
    COUNT(*) AS weekly_requests,
    COUNT(DISTINCT user_name) AS weekly_active_users,
    COUNT(DISTINCT service_name) AS services_used,
    LAG(weekly_requests) OVER (ORDER BY week_start) AS prev_week_requests,
    ROUND(100.0 * (weekly_requests - prev_week_requests) / NULLIF(prev_week_requests, 0), 2) AS wow_growth_pct
WHERE event_timestamp >= DATEADD('month', -3, CURRENT_TIMESTAMP())
GROUP BY week_start
ORDER BY week_start DESC;
-- SECTION 11 OBJECT INVENTORY
--   VW_QUERY_QUALITY              - Search effectiveness & zero-result tracking
--   VW_USER_FRUSTRATION_SIGNALS   - Repeated query / frustration detection
--   VW_ABUSE_DETECTION            - Rate limiting & bot detection
--   VW_SERVICE_REGISTRY           - Auto-discovered service catalog
-- NEW Materialized Views:
--   MVW_DAILY_TRENDS              - Pre-computed daily aggregates
-- NEW Views (GOVERNANCE):
-- NEW Functions (GOVERNANCE):
--   TBL_SERVICE_FRESHNESS_LOG     - Historical freshness snapshots
-- NEW Tasks:
--   TSK_FRESHNESS_CHECK           - 5-min freshness polling
-- END OF ELITE-TIER ENTERPRISE ENHANCEMENTS
-- ║ 12. FINAL HARDENING: SECURITY, RELIABILITY & PIPELINE INTEGRITY             ║
  TYPE = GENERIC_STRING
  SECRET_STRING = 'skrz2014@gamil.com';
    subject STRING,
    body STRING
  MODIFY COLUMN query_text
-- 12C. SECURITY: SCOPE ADMIN ROLE (REMOVE SYSADMIN INHERITANCE)
REVOKE ROLE FR_CORTEX_OBS_ADMIN FROM ROLE SYSADMIN;
-- 12D. RELIABILITY: IDEMPOTENT DAILY AGGREGATION TASK
        COUNT(*) AS total_requests,
        ROUND(100.0 * error_count / NULLIF(COUNT(*), 0), 2) AS error_rate_pct,
        ON pc.service_type = 'CORTEX_SEARCH'
        AND CURRENT_DATE() - 1 BETWEEN pc.effective_from AND COALESCE(pc.effective_to, '9999-12-31')
    WHERE e.TIMESTAMP >= DATEADD('day', -1, CURRENT_DATE())
      AND e.TIMESTAMP < CURRENT_DATE()
    RETURN 'Aggregation complete for ' || (CURRENT_DATE() - 1)::STRING;
    start_date DATE,
    end_date DATE
    current_dt DATE := :start_date;
    WHILE (current_dt <= end_date) DO
            COUNT(*) AS total_requests,
            ON pc.service_type = 'CORTEX_SEARCH'
            AND :current_dt BETWEEN pc.effective_from AND COALESCE(pc.effective_to, '9999-12-31')
        WHERE e.TIMESTAMP >= :current_dt
          AND e.TIMESTAMP < DATEADD('day', 1, :current_dt)
        current_dt := DATEADD('day', 1, :current_dt);
    RETURN 'Backfill complete: ' || :start_date::STRING || ' to ' || :end_date::STRING;
WITH historical AS (
        DAYOFWEEK(TIMESTAMP) AS dow,
        HOUR(TIMESTAMP) AS hr,
        COUNT(*) AS hourly_count
    WHERE TIMESTAMP >= DATEADD('day', -28, CURRENT_TIMESTAMP())
      AND TIMESTAMP < DATEADD('day', -1, CURRENT_TIMESTAMP())
    GROUP BY dow, hr, hour_bucket
    dow,
    hr,
    ROUND(AVG(hourly_count), 0) AS avg_requests,
    ROUND(STDDEV(hourly_count), 0) AS stddev_requests,
FROM historical
GROUP BY dow, hr
ORDER BY dow, hr;
        SELECT COUNT(*) AS current_count
    ) curr
        ON bl.dow = DAYOFWEEK(CURRENT_TIMESTAMP())
        AND bl.hr = HOUR(CURRENT_TIMESTAMP())
-- 12F. DATA QUALITY: CENTRALIZED PRICING CONFIG (SINGLE SOURCE OF TRUTH)
    service_type    STRING,
    effective_from  DATE,
    effective_to    DATE
USING (
    SELECT 'CORTEX_SEARCH' AS service_type,
           '2024-01-01'::DATE AS effective_from,
           NULL::DATE AS effective_to
) src
ON tgt.service_type = src.service_type AND tgt.effective_from = src.effective_from
WHEN NOT MATCHED THEN
-- 12G. DATA QUALITY: TIMEZONE-AWARE BASE VIEW
    CONVERT_TIMEZONE('UTC', 'America/New_York', event_timestamp) AS event_timestamp_et,
    CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', event_timestamp) AS event_timestamp_pt,
    DATE_TRUNC('day', CONVERT_TIMEZONE('UTC', 'America/New_York', event_timestamp)) AS business_day_et
  APPEND_ONLY = TRUE;
    COUNT(*) AS new_event_count,
    ROUND(100.0 * error_count / NULLIF(new_event_count, 0), 2) AS error_rate_pct
    ON 80 PERCENT DO NOTIFY
    'TSK_DAILY_AGGREGATION' AS check_name,
    END AS pipeline_status
    'EVENT_FLOW' AS check_name,
    MAX(TIMESTAMP)::DATE AS last_success_date,
    DATEDIFF('hour', MAX(TIMESTAMP), CURRENT_TIMESTAMP()) AS hours_since_last_run,
        WHEN DATEDIFF('hour', MAX(TIMESTAMP), CURRENT_TIMESTAMP()) > 2 THEN 'CRITICAL'
        WHEN DATEDIFF('hour', MAX(TIMESTAMP), CURRENT_TIMESTAMP()) > 1 THEN 'WARNING'
    'STREAM_LAG' AS check_name,
    CURRENT_DATE() AS last_success_date,
    NULL AS hours_since_last_run,
        ELSE 'CAUGHT_UP'
    END AS pipeline_status;
  SCHEDULE = '60 MINUTE'
    WHERE pipeline_status = 'CRITICAL'
    env_key     STRING,
    env_value   STRING,
    description STRING,
    updated_at  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    ('ADMIN_ROLE', 'FR_CORTEX_OBS_ADMIN', 'Admin functional role'),
    ('ANALYST_ROLE', 'FR_CORTEX_OBS_ANALYST', 'Read-only analyst role'),
    ('BUSINESS_TIMEZONE', 'America/New_York', 'Primary business timezone'),
    ('RETENTION_MONTHS', '24', 'Data retention period');
-- SECTION 12 OBJECT INVENTORY
-- NEW Secrets (GOVERNANCE):
--   SP_DAILY_AGGREGATION             - Idempotent daily rollup (DELETE+INSERT)
--   SP_BACKFILL_AGGREGATION          - Date-range backfill for missed runs
--   VW_VOLUME_BASELINE               - Weekday/hour-aware traffic baseline
-- NEW Tables (GOVERNANCE):
--   TBL_ENVIRONMENT_CONFIG           - Parameterized env configuration
--   STR_AI_EVENTS                    - Append-only stream for incremental processing
--   ALT_VOLUME_SPIKE_CONTEXTUAL      - Weekday/hour-aware spike detection
-- APPLIED POLICIES:
-- SECURITY CHANGES:
--   REVOKED FR_CORTEX_OBS_ADMIN FROM SYSADMIN
--   GRANTED FR_CORTEX_OBS_ADMIN TO SECURITYADMIN
-- END OF FINAL HARDENING
-- ╠══════════════════════════════════════════════════════════════════════════════╣
-- ║ PURPOSE:                                                                      ║
-- ║                                                                               ║
-- ║ EXECUTION:                                                                    ║
-- ║   T7  - Data Retention (tasks running, cleanup logic)                         ║
    expected_result     STRING,
    actual_result       STRING,
    passed              BOOLEAN,
    execution_time_ms   NUMBER,
    error_message       STRING,
    executed_at         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    executed_by         STRING DEFAULT CURRENT_USER()
    suite_run_id        STRING DEFAULT UUID_STRING(),
    started_at          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    completed_at        TIMESTAMP_NTZ,
    overall_status      STRING,
    run_duration_sec    NUMBER,
    triggered_by        STRING DEFAULT CURRENT_USER(),
    trigger_type        STRING DEFAULT 'MANUAL'
    FROM (SELECT 1 AS x);
            'PRD_CORTEX_OBS_XS_WH is available',
    -- T1.6: FR_CORTEX_OBS_READONLY role exists
    SELECT :suite_run_id, 'T1_INFRASTRUCTURE', 'T1.6', 'READONLY Role Exists',
            'FR_CORTEX_OBS_READONLY role is defined',
    -- T1.7: FR_CORTEX_OBS_ADMIN role exists
    SELECT :suite_run_id, 'T1_INFRASTRUCTURE', 'T1.7', 'ADMIN Role Exists',
            'FR_CORTEX_OBS_ADMIN role is defined',
    event_count NUMBER;
    search_event_count NUMBER;
    -- T2.1: Event table is accessible
    BEGIN
    EXCEPTION
    END;
    SELECT :suite_run_id, 'T2_EVENT_INGESTION', 'T2.1', 'Event Table Accessible',
    -- T2.2: Events are flowing (data within last 7d)
    SELECT COUNT(*) INTO event_count
    WHERE TIMESTAMP >= DATEADD('day', -7, CURRENT_TIMESTAMP());
    SELECT :suite_run_id, 'T2_EVENT_INGESTION', 'T2.2', 'Events Flowing (7d)',
            'At least 1 event in the last 7 days',
    SELECT COUNT(*) INTO search_event_count
    WHERE TIMESTAMP >= DATEADD('day', -7, CURRENT_TIMESTAMP())
    SELECT :suite_run_id, 'T2_EVENT_INGESTION', 'T2.3', 'Search Events Present (7d)',
      AND TIMESTAMP >= DATEADD('day', -7, CURRENT_TIMESTAMP());
    SELECT :suite_run_id, 'T2_EVENT_INGESTION', 'T2.4', 'Events Present in Window',
        LIMIT 1);
            'Key fields (object.name, response_time_ms) present in events',
    -- T2.6: Stream is tracking changes
    SELECT :suite_run_id, 'T2_EVENT_INGESTION', 'T2.6', 'Stream Exists & Functional',
            'STR_AI_EVENTS stream is operational',
    row_count NUMBER;
            'Base view compiles and executes without error',
    -- T3.3: VW_FAILED_REQUESTS compiles
            'Failed requests view compiles and executes',
    -- T3.4: VW_TOP_USERS compiles
            'Top users view compiles and executes',
    -- T3.6: VW_DAILY_TRENDS compiles
            'Daily trends view compiles and executes',
    -- T3.7: VW_ANOMALY_DETECTION compiles
            'Anomaly detection view compiles and executes',
    -- T3.10: VW_DATA_QUALITY compiles
            'Data quality view compiles and executes',
    -- T4.4: All severity levels are valid
                    WHERE severity NOT IN ('info', 'warning', 'critical'));
            'All severity values are info/warning/critical',
    -- T5.1: Pricing config table exists and has data
            'TBL_PRICING_CONFIG has at least one active rate',
            0
    SELECT :suite_run_id, 'T7_RETENTION', 'T7.1', 'Aggregation Table Exists',
    -- T7.2: No data older than 2 years in aggregation table
        SELECT COUNT(*) INTO row_count
    SELECT :suite_run_id, 'T7_RETENTION', 'T7.2', 'Retention Policy Enforced',
    -- T7.3: Daily aggregation task exists
        SELECT COUNT(*) INTO row_count FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "name" = 'TSK_DAILY_AGGREGATION';
    SELECT :suite_run_id, 'T7_RETENTION', 'T7.3', 'Daily Aggregation Task Active',
            'TSK_DAILY_AGGREGATION exists and is scheduled',
                        WHERE POLICY_NAME = 'MP_QUERY_TEXT_REDACT'
                          AND DELETED IS NULL);
    -- T8.3: Access audit view compiles
    SELECT :suite_run_id, 'T8_SECURITY', 'T8.3', 'VW_ACCESS_AUDIT Queryable',
            'Access audit view executes',
    -- T8.4: REDACT_SENSITIVE_QUERY function works
            'REDACT_SENSITIVE_QUERY detects credentials',
    -- T8.5: Environment config table has required keys
    SELECT :suite_run_id, 'T8_SECURITY', 'T8.5', 'Environment Config Populated',
            'TBL_ENVIRONMENT_CONFIG has required entries',
    query_time_ms NUMBER;
    -- T9.2: MVW_DAILY_TRENDS is queryable
    SELECT :suite_run_id, 'T9_PERFORMANCE', 'T9.2', 'MVW Daily Trends Queryable',
            'Materialized view MVW_DAILY_TRENDS executes',
    -- T9.3: Base view responds within 30 seconds
        query_time_ms := 0;
    SELECT :suite_run_id, 'T9_PERFORMANCE', 'T9.3', 'Base View Performance (<30s)',
    -- T9.4: NORMALIZE_QUERY function executes
    SELECT :suite_run_id, 'T9_PERFORMANCE', 'T9.4', 'NORMALIZE_QUERY Function Works',
            'Query fingerprinting function returns expected output',
    health_status STRING;
    -- T10.1: VW_PIPELINE_HEALTH compiles and returns status
    SELECT :suite_run_id, 'T10_PIPELINE_HEALTH', 'T10.1', 'Pipeline Health View Works',
    -- T10.2: Pipeline health is accessible and returns status
    SELECT :suite_run_id, 'T10_PIPELINE_HEALTH', 'T10.2', 'Pipeline Health Accessible',
            'Pipeline health view is queryable and returns status rows',
    -- T10.4: VW_VOLUME_BASELINE compiles
    SELECT :suite_run_id, 'T10_PIPELINE_HEALTH', 'T10.4', 'Volume Baseline View Works',
            'VW_VOLUME_BASELINE executes',
    -- T10.5: Service registry auto-discovers services
    SELECT :suite_run_id, 'T10_PIPELINE_HEALTH', 'T10.5', 'Service Registry Works',
            'VW_SERVICE_REGISTRY discovers services dynamically',
    -- T11.1: Base view handles NULL service_name gracefully
        WHERE service_name IS NULL;
    SELECT :suite_run_id, 'T11_RESILIENCE', 'T11.1', 'NULL Service Name Handling',
            'View handles NULL service_name without errors',
        WHERE response_time_ms = -1;
    -- T11.3: VW_QUERY_QUALITY handles zero-division
    SELECT :suite_run_id, 'T11_RESILIENCE', 'T11.3', 'Division-By-Zero Protected',
            'VW_QUERY_QUALITY uses NULLIF to prevent zero-division',
    -- T11.4: User frustration view handles empty data
    SELECT :suite_run_id, 'T11_RESILIENCE', 'T11.4', 'Frustration View Resilient',
            'VW_USER_FRUSTRATION_SIGNALS handles sparse data',
    -- T11.5: Abuse detection handles zero traffic
    SELECT :suite_run_id, 'T11_RESILIENCE', 'T11.5', 'Abuse Detection Handles Empty',
            'VW_ABUSE_DETECTION handles periods of zero traffic',
    view_count NUMBER;
    -- T12.1: Events flow through to base view (data consistency)
    SELECT COUNT(*) INTO view_count
    SELECT :suite_run_id, 'T12_INTEGRATION', 'T12.1', 'Event-to-View Data Flow',
    -- T12.3: Adoption trend produces week-over-week data
    SELECT :suite_run_id, 'T12_INTEGRATION', 'T12.3', 'Adoption Trend Produces Data',
            'VW_ADOPTION_TREND has weekly aggregation data',
    SELECT :suite_run_id, 'T12_INTEGRATION', 'T12.5', 'Object Deployment Complete',
RETURNS TABLE (
    actual_result STRING,
    execution_time_ms NUMBER
    suite_id STRING := UUID_STRING();
    total NUMBER;
    pass_count NUMBER;
    fail_count NUMBER;
    fail_count := total - pass_count;
    SET completed_at = CURRENT_TIMESTAMP(),
        overall_status = IFF(:fail_count = 0, 'ALL_PASSED', 'HAS_FAILURES'),
        run_duration_sec = 0
    WHERE suite_run_id = :suite_id;
  SCHEDULE = 'USING CRON 0 * * * * UTC'
    WHERE completed_at >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
      AND overall_status = 'HAS_FAILURES'
    suite_run_id,
    started_at,
    completed_at,
    overall_status,
    run_duration_sec,
    triggered_by,
    trigger_type
ORDER BY started_at DESC;
    tr.expected_result,
    tr.actual_result,
    tr.execution_time_ms,
    tr.executed_at
JOIN (
    SELECT suite_run_id
    ORDER BY started_at DESC
    LIMIT 1
WHERE tr.passed = FALSE
    COUNT(*) AS runs_per_day,
    AVG(pass_rate_pct) AS avg_pass_rate,
    MIN(pass_rate_pct) AS min_pass_rate,
    COUNT_IF(overall_status = 'HAS_FAILURES') AS failed_runs,
    AVG(run_duration_sec) AS avg_duration_sec
WHERE started_at >= DATEADD('month', -1, CURRENT_TIMESTAMP())
-- 13Q. QUICK EXECUTION COMMANDS
-- View pass rate trend over time:
-- SECTION 13 OBJECT INVENTORY
-- TABLES:
-- TASKS:
-- VIEWS:
    total_requests NUMBER;
    distinct_services NUMBER;
    distinct_users NUMBER;
    error_rate NUMBER;
    pass_rate NUMBER;
    p95_status STRING;
    p99_status STRING;
    SELECT COUNT(*), COUNT(DISTINCT service_name), COUNT(DISTINCT user_name),
           ROUND(AVG(response_time_ms), 1),
           ROUND(100.0 * COUNT_IF(status_code != 200) / NULLIF(COUNT(*), 0), 1)
    SELECT COUNT(*), COUNT_IF(passed = TRUE), COUNT_IF(passed = FALSE)
        ORDER BY started_at DESC LIMIT 1
    p95_status := 'Compliant';
    p99_status := 'Compliant';
      || '<body style="margin:0;padding:0;background-color:#F7F9FB;font-family:Arial,Helvetica,sans-serif;">'
      || '<table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="background-color:#F7F9FB;"><tr><td align="center" style="padding:24px 16px;">'
      || '<table role="presentation" cellpadding="0" cellspacing="0" width="640" style="max-width:640px;width:100%;">'
      || '<tr><td style="background:linear-gradient(135deg,#0F2A44 0%,#1B3A5C 100%);border-radius:12px 12px 0 0;padding:40px 32px 32px;">'
      || '<table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr><td>'
      || '</td><td align="right" valign="top">'
      || '<table role="presentation" cellpadding="0" cellspacing="0"><tr><td style="background-color:rgba(41,181,232,0.15);border:1px solid rgba(41,181,232,0.3);border-radius:6px;padding:8px 14px;">'
      || '<p style="margin:2px 0 0;font-size:15px;font-weight:700;color:#FFFFFF;">' || TO_CHAR(CURRENT_DATE(), 'Mon DD, YYYY') || '</p>'
      || '</td></tr></table></td></tr></table></td></tr>'
      || '<tr><td style="background-color:#FFFFFF;border-left:1px solid #E5E7EB;border-right:1px solid #E5E7EB;padding:24px 32px;">'
      || '<table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr>'
      || '<td width="33%" style="padding-right:12px;"><table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr><td style="background-color:#ECFDF5;border:1px solid #A7F3D0;border-radius:8px;padding:16px;text-align:center;">'
      || '<p style="margin:0;font-size:11px;color:#065F46;text-transform:uppercase;letter-spacing:0.5px;font-weight:600;">Platform Health</p>'
      || '<p style="margin:6px 0 0;font-size:28px;font-weight:800;color:#059669;">' || pass_rate::STRING || '%</p>'
      || '</td></tr></table></td>'
      || '<td width="33%" style="padding:0 6px;"><table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr><td style="background-color:#ECFDF5;border:1px solid #A7F3D0;border-radius:8px;padding:16px;text-align:center;">'
      || '<p style="margin:0;font-size:11px;color:#065F46;text-transform:uppercase;letter-spacing:0.5px;font-weight:600;">Risk Level</p>'
      || '<p style="margin:6px 0 0;font-size:28px;font-weight:800;color:#059669;">LOW</p>'
      || '<td width="33%" style="padding-left:12px;"><table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr><td style="background-color:#ECFDF5;border:1px solid #A7F3D0;border-radius:8px;padding:16px;text-align:center;">'
      || '<p style="margin:0;font-size:11px;color:#065F46;text-transform:uppercase;letter-spacing:0.5px;font-weight:600;">Action Required</p>'
      || '<p style="margin:6px 0 0;font-size:28px;font-weight:800;color:#059669;">NO</p>'
      || '<p style="margin:4px 0 0;font-size:12px;color:#047857;">Fully operational</p>'
      || '<tr><td style="background-color:#FFFFFF;border-left:1px solid #E5E7EB;border-right:1px solid #E5E7EB;padding:0 32px;"><table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr><td style="border-top:1px solid #F3F4F6;height:1px;font-size:1px;line-height:1px;">&nbsp;</td></tr></table></td></tr>'
      || '<td width="33%" style="padding:0 8px 8px 0;"><table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr><td style="background-color:#F8FAFC;border:1px solid #E5E7EB;border-radius:8px;padding:14px;text-align:center;">'
      || '<p style="margin:0;font-size:24px;font-weight:800;color:#0F2A44;">' || total_requests::STRING || '</p>'
      || '<p style="margin:4px 0 0;font-size:11px;color:#6B7280;">Requests (7d)</p></td></tr></table></td>'
      || '<td width="33%" style="padding:0 4px 8px;"><table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr><td style="background-color:#F8FAFC;border:1px solid #E5E7EB;border-radius:8px;padding:14px;text-align:center;">'
      || '<p style="margin:0;font-size:24px;font-weight:800;color:#0F2A44;">' || distinct_services::STRING || '</p>'
      || '<p style="margin:4px 0 0;font-size:11px;color:#6B7280;">Active Services</p></td></tr></table></td>'
      || '<td width="33%" style="padding:0 0 8px 8px;"><table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr><td style="background-color:#F8FAFC;border:1px solid #E5E7EB;border-radius:8px;padding:14px;text-align:center;">'
      || '<p style="margin:0;font-size:24px;font-weight:800;color:#0F2A44;">' || distinct_users::STRING || '</p>'
      || '<p style="margin:4px 0 0;font-size:11px;color:#6B7280;">Unique Users</p></td></tr></table></td>'
      || '</tr><tr>'
      || '<td width="33%" style="padding:0 8px 0 0;"><table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr><td style="background-color:#F8FAFC;border:1px solid #E5E7EB;border-radius:8px;padding:14px;text-align:center;">'
      || '<td width="33%" style="padding:0 4px 0;"><table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr><td style="background-color:' || IFF(error_rate > 5, '#FEF2F2;border:1px solid #FECACA', '#F8FAFC;border:1px solid #E5E7EB') || ';border-radius:8px;padding:14px;text-align:center;">'
      || '<p style="margin:0;font-size:24px;font-weight:800;color:' || IFF(error_rate > 5, '#DC2626', '#0F2A44') || ';">' || error_rate::STRING || '<span style="font-size:14px;">%</span></p>'
      || '<td width="33%" style="padding:0 0 0 8px;"><table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr><td style="background-color:#F8FAFC;border:1px solid #E5E7EB;border-radius:8px;padding:14px;text-align:center;">'
      || '<p style="margin:0;font-size:24px;font-weight:800;color:#059669;">' || view_count::STRING || '</p>'
      || '</tr></table></td></tr>'
      || '<table role="presentation" cellpadding="0" cellspacing="0" width="100%">'
      || '<tr><td style="padding:10px 0;border-bottom:1px solid #F3F4F6;"><table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr>'
      || '<td align="right"><span style="display:inline-block;background-color:#ECFDF5;color:#059669;font-size:11px;font-weight:700;padding:4px 10px;border-radius:12px;">COMPLIANT</span></td>'
      || '<tr><td style="padding:10px 0;"><table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr>'
      || '</tr></table></td></tr></table></td></tr>'
      || '<h2 style="margin:0 0 16px;font-size:14px;font-weight:700;color:#0F2A44;text-transform:uppercase;letter-spacing:0.5px;">Infrastructure &amp; Security</h2>'
      || '<td style="padding:6px 0;"><span style="color:#059669;font-weight:700;">&#10003;</span> <span style="font-size:13px;color:#374151;">SOC2/GDPR/HIPAA</span></td></tr>'
      || '</table></td></tr>'
      || '<tr><td style="background-color:#0F2A44;border-radius:0 0 12px 12px;padding:24px 32px;">'
      || '<p style="margin:4px 0 0;font-size:11px;color:#6B8299;">Account: zt86108 | Next scheduled run: Hourly</p></td>'
      || '<td align="right"><p style="margin:0;font-size:11px;color:#6B8299;">Powered by</p>'
      || '<p style="margin:2px 0 0;font-size:13px;font-weight:700;color:#29B5E8;">Snowflake Cortex</p></td>'
-- ║ 15. EXECUTED FIXES & LIVE DEPLOYMENT (Production Validated)                   ║
    WHERE event_timestamp >= DATEADD('minute', -5, CURRENT_TIMESTAMP())
      AND response_time_ms > 3000
    HAVING COUNT(*) > 5
    HAVING COUNT_IF(status_code != 200) * 100.0 / NULLIF(COUNT(*), 0) > 5
    HAVING COUNT(*) > 10000
      'Request volume exceeded 10000 in the last hour.'
    GROUP BY user_name
      'High request rate detected from a single user.'
-- 15C. DAILY AGGREGATION TASK
  SCHEDULE = 'USING CRON 15 2 * * * UTC'
  BEGIN
      COUNT(*) AS total_requests,
    WHERE TIMESTAMP >= DATEADD('day', -1, CURRENT_DATE())
      AND TIMESTAMP < CURRENT_DATE()
    GROUP BY service_name, user_name, role_name;
    id NUMBER AUTOINCREMENT,
    title STRING,
    content STRING,
    category STRING,
    ('Snowflake Architecture', 'Snowflake is a cloud-native data platform with a multi-cluster shared data architecture separating storage, compute, and services.', 'ARCHITECTURE'),
    ('Cortex Analyst', 'Cortex Analyst converts natural language questions into SQL using semantic models defined in YAML.', 'AI'),
    ('Data Sharing', 'Secure data sharing allows sharing live data across accounts without copying, using reader accounts or direct shares.', 'GOVERNANCE'),
    ('Streams and Tasks', 'Streams capture change data (CDC) on tables. Tasks schedule SQL execution on a recurring basis or triggered by streams.', 'PIPELINES'),
    ('Network Policies', 'Network policies restrict access to Snowflake based on IP address ranges, supporting allow and block lists.', 'SECURITY'),
    ('Materialized Views', 'Materialized views pre-compute and store query results, automatically refreshing when base table data changes.', 'PERFORMANCE'),
    ('External Functions', 'External functions call remote APIs from SQL, enabling integration with external services and ML models.', 'INTEGRATION');
-- NOTE: Requires non-trial account with EMBED_TEXT_768 access
--   ON content
--   ATTRIBUTES category, title
--   TARGET_LAG = '1 minute'
--   AS (
--     SELECT id, title, content, category
--   );
  SCHEDULE = 'USING CRON 0 8 * * 1 UTC'
-- SECTION 14-15 OBJECT INVENTORY
--   ALT_SPIKE_VOLUME                - 1-hour count > 10000
--   ALT_ABUSE_DETECTED              - Per-user 1-hour > 10000
--   ALT_PIPELINE_STALE              - Pipeline health CRITICAL
--   TSK_DAILY_AGGREGATION           - 2:15 AM UTC daily rollup
-- END OF EXECUTED FIXES & LIVE DEPLOYMENT
-- ║ 16. ARCHITECT-REVIEW CRITICAL FIXES & STRATEGIC ADDITIONS                     ║
-- ║  • ACCESS_HISTORY:                       45-120 minute delay                  ║
-- ║  • QUERY_HISTORY:                        45-120 minute delay                  ║
-- ║  • CORTEX_SEARCH_DAILY_USAGE_HISTORY:    24-hour delay                        ║
SELECT *
WHERE event_timestamp <= DATEADD('minute', -3, CURRENT_TIMESTAMP());
    last_fired TIMESTAMP_NTZ,
    last_resolved TIMESTAMP_NTZ,
    current_state STRING,
    fire_count NUMBER DEFAULT 0
    last_fired_ts TIMESTAMP_NTZ;
    should_fire BOOLEAN;
        SELECT last_fired INTO last_fired_ts
        WHEN OTHER THEN last_fired_ts := NULL;
    should_fire := (last_fired_ts IS NULL OR DATEDIFF('minute', last_fired_ts, CURRENT_TIMESTAMP()) >= 15);
    IF (should_fire) THEN
        WHEN MATCHED THEN UPDATE SET last_fired = CURRENT_TIMESTAMP(), current_state = 'FIRING', fire_count = fire_count + 1
        RETURN TRUE;
    END IF;
    RETURN FALSE;
    SET last_resolved = CURRENT_TIMESTAMP(), current_state = 'RESOLVED'
    RETURN TRUE;
    AVG(result_limit) AS avg_result_limit,
    COUNT_IF(result_limit = 0 OR result_limit IS NULL) AS no_limit_requests,
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY response_time_ms) AS p50_ms,
    PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY response_time_ms) AS p95_ms,
    COUNT(DISTINCT query_text) AS unique_queries,
    COUNT(*) - COUNT(DISTINCT query_text) AS repeated_queries,
    ROUND(100.0 * repeated_queries / NULLIF(request_count, 0), 2) AS query_repetition_pct
-- 16D. ERROR CLASSIFICATION VIEW
    status_code,
        WHEN status_code = 429 THEN 'RATE_LIMITED'
        WHEN status_code = 401 OR status_code = 403 THEN 'AUTH_ERROR'
        WHEN status_code BETWEEN 400 AND 499 THEN 'CLIENT_ERROR'
        WHEN status_code BETWEEN 500 AND 599 THEN 'SERVER_ERROR'
        ELSE 'UNKNOWN'
    END AS error_category,
    COUNT(*) AS occurrences,
    COUNT(DISTINCT user_name) AS affected_users,
    COUNT(DISTINCT query_text) AS distinct_queries
WHERE status_code != 200 AND status_code != -1
GROUP BY status_code, error_category, service_name, hour_bucket
ORDER BY hour_bucket DESC, occurrences DESC;
WITH current_fields AS (
    SELECT DISTINCT f.key
    LATERAL FLATTEN(INPUT => e.RECORD_ATTRIBUTES) f
    WHERE e.TIMESTAMP >= DATEADD('day', -1, CURRENT_TIMESTAMP())
baseline_fields AS (
    WHERE e.TIMESTAMP BETWEEN DATEADD('day', -8, CURRENT_TIMESTAMP())
        AND DATEADD('day', -1, CURRENT_TIMESTAMP())
    c.key AS new_field_name,
    'RECORD_ATTRIBUTES' AS source_column,
    CURRENT_TIMESTAMP() AS detected_at
FROM current_fields c
LEFT JOIN baseline_fields b ON c.key = b.key
WHERE b.key IS NULL;
    WHERE usage_date = CURRENT_DATE()
    change_id STRING DEFAULT UUID_STRING(),
    change_timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    changed_by STRING DEFAULT CURRENT_USER(),
    action STRING,
    old_severity STRING,
    new_severity STRING
  APPEND_ONLY = FALSE;
  SELECT
    METADATA$ACTION,
    SERVICE_NAME,
    SEVERITY
        WHEN REGEXP_LIKE(query_text, '.*(^|[^0-9])\\d{3}-\\d{2}-\\d{4}([^0-9]|$).*')
            THEN REGEXP_REPLACE(query_text, '\\d{3}-\\d{2}-\\d{4}', '***SSN***')
        WHEN REGEXP_LIKE(query_text, '.*(^|[^0-9])\\d{4}[ -]?\\d{4}[ -]?\\d{4}[ -]?\\d{4}([^0-9]|$).*')
            AND NOT REGEXP_LIKE(query_text, '.*(version|timestamp|datetime|order.?number|id|code).*', 'i')
            THEN REGEXP_REPLACE(query_text, '\\d{4}[ -]?\\d{4}[ -]?\\d{4}[ -]?\\d{4}', '***CC***')
        WHEN REGEXP_LIKE(query_text, '.*[A-Za-z0-9][A-Za-z0-9._%+-]*@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}.*')
        WHEN REGEXP_LIKE(query_text, '.*(password|passwd|pwd|secret|token|api.key).*', 'i')
            THEN '***CREDENTIAL_DETECTED***'
-- 16I. MATURITY LEVEL 6: ML-POWERED ANOMALY DETECTION (FUTURE)
-- NOTE: Uncomment when sufficient historical data exists (4+ weeks recommended)
-- CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION
--     TIMESTAMP_COLNAME => 'day_bucket',
--     TARGET_COLNAME => 'daily_requests',
--     LABEL_COLNAME => ''
-- );
-- NOTE: Uncomment for ML-based forecasting
-- CREATE OR REPLACE SNOWFLAKE.ML.FORECAST
--     SERIES_COLNAME => 'service_name',
--     TARGET_COLNAME => 'daily_requests'
-- SECTION 16 OBJECT INVENTORY
--   VW_ERROR_CLASSIFICATION        - Error categorization (4xx/5xx/rate-limit)
--   REDACT_SENSITIVE_QUERY_V2      - Reduced false positives
-- NEW Streams:
-- FUTURE (commented):
--   AD_VOLUME_ANOMALIES            - ML anomaly detection
--   FCAST_DAILY_REQUESTS           - ML forecasting
-- END OF ARCHITECT-REVIEW FIXES
-- ║ 17. PRINCIPAL ARCHITECT STRATEGIC ENHANCEMENTS                                ║
-- ║     Dynamic Tables, Clustering, Pipeline Guards, Self-Documentation           ║
-- 17A. DYNAMIC TABLES (REPLACE MANUAL TASK-BASED AGGREGATION)
  TARGET_LAG = '5 minutes'
    ROUND(100.0 * COUNT_IF(status_code != 200) / NULLIF(COUNT(*), 0), 2) AS error_rate_pct,
    COUNT(DISTINCT query_text) AS unique_queries
GROUP BY hour_bucket, service_name, user_name, role_name;
  TARGET_LAG = '30 minutes'
    DATE_TRUNC('day', hour_bucket) AS day_bucket,
    SUM(request_count) AS daily_requests,
    COUNT(DISTINCT user_name) AS daily_active_users,
    MAX(p95_ms) AS peak_p95_ms,
    SUM(error_count) AS daily_errors,
    ROUND(100.0 * SUM(error_count) / NULLIF(SUM(request_count), 0), 2) AS daily_error_rate_pct
GROUP BY day_bucket, service_name;
-- 17B. ENHANCED BASE VIEW (FINGERPRINT + INGESTION LAG)
    SHA2(COALESCE(query_text, 'NULL') || '|' || COALESCE(user_name, ''), 256) AS request_fingerprint,
    DATEDIFF('second', event_timestamp, CURRENT_TIMESTAMP()) AS ingestion_lag_seconds,
        WHEN query_text IS NULL OR query_text = 'NULL_QUERY' OR TRIM(query_text) = '' THEN 'EMPTY_QUERY'
        ELSE REGEXP_REPLACE(query_text, '\\s+', ' ')
    END AS cleaned_query
-- 17C. CLUSTERING FOR PERFORMANCE
  SCHEDULE = '15 MINUTE'
  IF (NOT EXISTS (
    WHERE TIMESTAMP >= DATEADD('minute', -30, CURRENT_TIMESTAMP())
      'NO_EVENTS_30MIN',
-- 17E. SELF-DOCUMENTING OBJECT INVENTORY VIEW
    'VIEW' AS object_type,
    TABLE_NAME AS object_name,
    CREATED AS created_at,
    LAST_ALTERED AS last_modified,
    COMMENT AS description
    'TABLE' AS object_type,
    TABLE_NAME,
    CREATED,
    LAST_ALTERED,
    COMMENT
  AND TABLE_TYPE = 'BASE TABLE'
    'PROCEDURE' AS object_type,
    PROCEDURE_NAME,
    'FUNCTION' AS object_type,
    FUNCTION_NAME,
  ALLOWED_VALUES = 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED';
  ALLOWED_VALUES = 'AI_PLATFORM', 'SECURITY_OPS', 'FINANCE', 'ENGINEERING';
    DATE_TRUNC('week', day_bucket) AS week_start,
    SUM(daily_requests) AS weekly_requests,
    SUM(daily_active_users) AS weekly_active_users,
    MAX(peak_p95_ms) AS peak_p95_ms,
    SUM(daily_errors) AS weekly_errors,
    ROUND(100.0 * SUM(daily_errors) / NULLIF(SUM(daily_requests), 0), 2) AS weekly_error_rate_pct
GROUP BY week_start, service_name
    r.role_name AS team_identifier,
    SUM(r.request_count) AS total_requests,
WHERE r.usage_date >= DATEADD('month', -3, CURRENT_DATE())
    CURRENT_TIMESTAMP() AS measured_at,
    ROUND(100.0 * healthy_pipelines / NULLIF(total_pipelines, 0), 0) AS pipeline_health_pct,
        ELSE 'CRITICAL'
    END AS overall_health_grade;
      QUERY_ACCELERATION_MAX_SCALE_FACTOR = 4;
--   MIN_CLUSTER_COUNT = 1
--   MAX_CLUSTER_COUNT = 3
--   SCALING_POLICY = 'ECONOMY'
--   AUTO_SUSPEND = 120
--   AUTO_RESUME = TRUE
-- SECTION 17 OBJECT INVENTORY
-- NEW Dynamic Tables (AGGREGATED):
--   DT_DAILY_SERVICE_SUMMARY       - 30-min lag, daily service-level KPIs
--   VW_OBJECT_INVENTORY            - Self-documenting catalog of all objects
--   VW_EXEC_WEEKLY_SUMMARY         - BI-optimized weekly executive view
--   VW_PLATFORM_HEALTH_SCORE       - Single health grade (EXCELLENT/GOOD/DEGRADED)
--   ALT_NO_EVENTS_30MIN            - Pipeline dead detection
-- NEW Tags (GOVERNANCE):
--   TAG_SENSITIVITY                - PUBLIC, INTERNAL, CONFIDENTIAL, RESTRICTED
-- MODIFIED:
-- END OF PRINCIPAL ARCHITECT STRATEGIC ENHANCEMENTS